create role anon nologin; create role authenticated nologin; create role service_role nologin;
create schema auth; create schema private; create schema storage; create schema cron;
create table auth.users (id uuid primary key default gen_random_uuid(), email text);
create or replace function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$;
create type public.app_role as enum ('user','agent','admin','super_admin');
create table public.user_roles (user_id uuid, role public.app_role);
create function private.has_role(u uuid, r public.app_role) returns boolean language sql stable as $$ select exists(select 1 from public.user_roles where user_id=u and role=r) $$;
create type public.notification_kind as enum ('booking','message','wallet','listing','agent','support','system','social');
create table public.notifications (id uuid primary key default gen_random_uuid(), user_id uuid, kind public.notification_kind, title text, body text, href text, created_at timestamptz default now());
create function private.notify(u uuid, k public.notification_kind, t text, b text, h text) returns void language sql as $$ insert into public.notifications(user_id,kind,title,body,href) values (u,k,t,b,h) $$;
create table public.email_outbox (id uuid primary key default gen_random_uuid(), user_id uuid, template text, dedupe_key text unique, payload jsonb);
create function private.email_outbox_enqueue(u uuid, t text, k text, p jsonb) returns void language sql as $$ insert into public.email_outbox(user_id,template,dedupe_key,payload) values (u,t,k,p) on conflict do nothing $$;
create table public.audit_log (id uuid primary key default gen_random_uuid(), actor_id uuid, action text, entity_type text, entity_id text, metadata jsonb, created_at timestamptz default now());
create table public.risk_alerts (id uuid primary key default gen_random_uuid(), severity text, status text, title text, description text, entity_type text, entity_id text);
create table public.agents (id uuid primary key default gen_random_uuid(), user_id uuid references auth.users);
create type public.rate_period as enum ('night','month','year');
create table public.listings (id uuid primary key default gen_random_uuid(), agent_id uuid references public.agents, title text, status text default 'PUBLISHED', listing_intent text, rent_amount_minor bigint, caution_deposit_minor bigint, service_charge_minor bigint, agency_fee_minor bigint, legal_fee_minor bigint, agreement_fee_minor bigint, total_move_in_cost_minor bigint, rent_period public.rate_period, rate_period public.rate_period);
create type public.inspection_state as enum ('REQUESTED','CONFIRMED','PROPOSED','DECLINED','COMPLETED','WITHDRAWN');
create table public.inspection_requests (id uuid primary key default gen_random_uuid(), listing_id uuid references public.listings, requester_id uuid, lister_id uuid, state public.inspection_state, outcome text);
create table public.inspection_reports (inspection_id uuid primary key references public.inspection_requests, author_id uuid, notes text, submitted_at timestamptz);
create table public.inspection_report_items (inspection_id uuid, item text, checked boolean);
create table public.inspection_report_photos (id uuid primary key default gen_random_uuid(), inspection_id uuid, item text, storage_path text);
create type public.booking_status as enum ('PENDING','CONFIRMED','COMPLETED','NO_SHOW','CANCELLED');
create table public.bookings (id uuid primary key default gen_random_uuid(), listing_id uuid references public.listings, guest_id uuid, check_in date, check_out date, nights int default 1, adults int default 1, children int default 0, price_per_night_minor bigint default 0, cleaning_fee_minor bigint default 0, service_fee_minor bigint default 0, subtotal_minor bigint default 0, total_minor bigint, currency text default 'NGN', status public.booking_status default 'PENDING', created_at timestamptz default now(), updated_at timestamptz default now());
create table public.booking_state_events (id uuid primary key default gen_random_uuid(), booking_id uuid, from_status public.booking_status, to_status public.booking_status, actor_id uuid, note text, created_at timestamptz default now());
create table public.availability (listing_id uuid, date date, status text, primary key (listing_id, date));
create type public.transaction_status as enum ('SUCCESSFUL','PENDING','FAILED','REFUNDED');
create table public.transactions (id uuid primary key default gen_random_uuid(), booking_id uuid references public.bookings, provider text, provider_ref text unique, amount_minor bigint check (amount_minor>=0), currency text, status public.transaction_status, created_at timestamptz default now(), updated_at timestamptz default now());
create table public.ledger_entries (id uuid primary key default gen_random_uuid(), booking_id uuid, transaction_id uuid references public.transactions, gross_minor bigint, platform_fee_minor bigint, agent_share_minor bigint, processor_fee_minor bigint, net_settlement_minor bigint, created_at timestamptz default now(), constraint ledger_balances_chk check (gross_minor = platform_fee_minor + agent_share_minor + processor_fee_minor));
create unique index on public.ledger_entries (transaction_id) where transaction_id is not null;
create table public.booking_refunds (id uuid primary key default gen_random_uuid(), booking_id uuid, guest_id uuid, paid_minor bigint, refund_minor bigint, retained_minor bigint, reason text, note text, wallet_reference text unique, wallet_entry_id uuid, decided_by uuid, created_at timestamptz default now());
create table public.rent_payments (id uuid primary key default gen_random_uuid(), inspection_id uuid, listing_id uuid, tenant_id uuid, lister_id uuid, booking_id uuid, total_minor bigint);
create table public.rent_refunds_owed (booking_id uuid primary key, lister_id uuid, amount_minor bigint check (amount_minor>0), created_at timestamptz default now(), updated_at timestamptz default now(), cleared_at timestamptz);
create type public.fee_kind as enum ('commission','listing_fee');
create table public.fee_rates (id uuid primary key default gen_random_uuid(), kind public.fee_kind, basis_points int, effective_from timestamptz default now());
create type public.document_review_status as enum ('pending','approved','rejected');
create table public.listing_mandates (id uuid primary key default gen_random_uuid(), listing_id uuid, review_status public.document_review_status, expires_on date, reviewed_at timestamptz, principal_consent_withdrawn_at timestamptz);
create table public.payout_accounts (id uuid primary key default gen_random_uuid(), agent_id uuid references public.agents, is_default boolean default true, created_at timestamptz default now(), account_number text, bank_code text);
create function private.listing_is_let(l uuid, b uuid) returns boolean language sql as $$ select false $$;
create table storage.buckets (id text primary key, name text, public boolean, file_size_limit bigint, allowed_mime_types text[]);
create table storage.objects (id uuid primary key default gen_random_uuid(), bucket_id text, name text);
alter table storage.objects enable row level security;
create function storage.foldername(n text) returns text[] language sql as $$ select string_to_array(n,'/') $$;
