-- M8 seed: curated Lagos and Abuja landmarks. DRAFT. NOT APPLIED.
--
-- Mirrors supabase/migrations/pending/LANDMARKS.md one for one. Applied only
-- after the founder approves that page; a struck row there is deleted here
-- before applying. Coordinates are hand-placed and approximate; nothing is
-- scraped. Every row is first_party curation. Idempotent on slug so the seed
-- can be re-run after a correction.

insert into public.landmarks (name, slug, kind, state_code, city, latitude, longitude, aliases) values
  -- Lagos
  ('Murtala Muhammed International Airport', 'murtala-muhammed-international-airport', 'airport', 'LA', 'Lagos', 6.5774, 3.3212, array['MMIA', 'Lagos airport', 'international airport']),
  ('Murtala Muhammed Airport Terminal 2', 'murtala-muhammed-airport-terminal-2', 'airport', 'LA', 'Lagos', 6.5830, 3.3250, array['MMA2', 'domestic airport', 'local airport']),
  ('Victoria Island', 'victoria-island', 'business_district', 'LA', 'Lagos', 6.4281, 3.4219, array['VI', 'V.I.']),
  ('Ikoyi', 'ikoyi', 'business_district', 'LA', 'Lagos', 6.4500, 3.4350, array[]::text[]),
  ('Lekki Phase 1', 'lekki-phase-1', 'business_district', 'LA', 'Lagos', 6.4478, 3.4723, array['Lekki 1', 'Lekki Phase One']),
  ('Ikeja GRA', 'ikeja-gra', 'business_district', 'LA', 'Lagos', 6.5833, 3.3500, array['GRA Ikeja']),
  ('Lagos Island', 'lagos-island', 'business_district', 'LA', 'Lagos', 6.4530, 3.3958, array['Marina', 'Broad Street', 'Isale Eko']),
  ('Eko Atlantic', 'eko-atlantic', 'business_district', 'LA', 'Lagos', 6.4150, 3.4100, array['Eko Atlantic City']),
  ('Yaba', 'yaba', 'business_district', 'LA', 'Lagos', 6.5095, 3.3711, array['Yabacon']),
  ('Surulere', 'surulere', 'other', 'LA', 'Lagos', 6.4969, 3.3560, array[]::text[]),
  ('Ajah', 'ajah', 'other', 'LA', 'Lagos', 6.4670, 3.5700, array[]::text[]),
  ('Festac Town', 'festac-town', 'other', 'LA', 'Lagos', 6.4667, 3.2833, array['Festac']),
  ('Magodo', 'magodo', 'other', 'LA', 'Lagos', 6.6100, 3.3800, array['Magodo GRA']),
  ('Ikeja City Mall', 'ikeja-city-mall', 'mall', 'LA', 'Lagos', 6.6140, 3.3580, array['ICM']),
  ('The Palms Shopping Mall', 'the-palms-shopping-mall', 'mall', 'LA', 'Lagos', 6.4350, 3.4590, array['The Palms', 'Palms Lekki']),
  ('Maryland Mall', 'maryland-mall', 'mall', 'LA', 'Lagos', 6.5720, 3.3660, array[]::text[]),
  ('Balogun Market', 'balogun-market', 'market', 'LA', 'Lagos', 6.4560, 3.3880, array[]::text[]),
  ('Computer Village', 'computer-village', 'market', 'LA', 'Lagos', 6.5960, 3.3420, array['Computer Village Ikeja']),
  ('Teslim Balogun Stadium', 'teslim-balogun-stadium', 'stadium', 'LA', 'Lagos', 6.5030, 3.3620, array[]::text[]),
  ('National Stadium Surulere', 'national-stadium-surulere', 'stadium', 'LA', 'Lagos', 6.4970, 3.3640, array['National Stadium Lagos']),
  ('Landmark Beach', 'landmark-beach', 'beach', 'LA', 'Lagos', 6.4180, 3.4480, array['Landmark']),
  ('Elegushi Beach', 'elegushi-beach', 'beach', 'LA', 'Lagos', 6.4235, 3.5030, array['Elegushi']),
  ('Tarkwa Bay', 'tarkwa-bay', 'beach', 'LA', 'Lagos', 6.4060, 3.3990, array['Tarkwa Bay Beach']),
  ('Lekki Conservation Centre', 'lekki-conservation-centre', 'park', 'LA', 'Lagos', 6.4416, 3.5350, array['LCC', 'canopy walk']),
  ('Freedom Park', 'freedom-park', 'park', 'LA', 'Lagos', 6.4500, 3.3940, array[]::text[]),
  ('National Theatre', 'national-theatre', 'other', 'LA', 'Lagos', 6.4730, 3.3670, array[]::text[]),
  ('Eko Hotels and Suites', 'eko-hotels-and-suites', 'other', 'LA', 'Lagos', 6.4270, 3.4290, array['Eko Hotel']),
  ('Lagos University Teaching Hospital', 'lagos-university-teaching-hospital', 'hospital', 'LA', 'Lagos', 6.5170, 3.3540, array['LUTH']),
  ('University of Lagos', 'university-of-lagos', 'education', 'LA', 'Lagos', 6.5158, 3.3862, array['UNILAG', 'Unilag Akoka']),
  ('Lagos Business School', 'lagos-business-school', 'education', 'LA', 'Lagos', 6.4330, 3.5480, array['LBS']),
  ('Oshodi Transport Interchange', 'oshodi-transport-interchange', 'transport', 'LA', 'Lagos', 6.5550, 3.3400, array['Oshodi']),
  ('Ojota Motor Park', 'ojota-motor-park', 'transport', 'LA', 'Lagos', 6.5870, 3.3830, array['Ojota']),
  ('Apapa Port', 'apapa-port', 'transport', 'LA', 'Lagos', 6.4480, 3.3620, array['Apapa', 'Apapa Wharf']),
  ('Cathedral Church of Christ, Marina', 'cathedral-church-of-christ-marina', 'worship', 'LA', 'Lagos', 6.4530, 3.3930, array[]::text[]),
  ('Lagos Central Mosque', 'lagos-central-mosque', 'worship', 'LA', 'Lagos', 6.4540, 3.3900, array['Central Mosque Lagos']),
  -- Abuja
  ('Nnamdi Azikiwe International Airport', 'nnamdi-azikiwe-international-airport', 'airport', 'FC', 'Abuja', 9.0068, 7.2632, array['ABV', 'Abuja airport']),
  ('Maitama', 'maitama', 'business_district', 'FC', 'Abuja', 9.0870, 7.4950, array[]::text[]),
  ('Wuse 2', 'wuse-2', 'business_district', 'FC', 'Abuja', 9.0770, 7.4780, array['Wuse II', 'Wuse Two']),
  ('Central Business District', 'central-business-district', 'business_district', 'FC', 'Abuja', 9.0500, 7.4900, array['CBD', 'Central Area']),
  ('Garki', 'garki', 'business_district', 'FC', 'Abuja', 9.0330, 7.4900, array['Garki Area 11', 'Area 11']),
  ('Asokoro', 'asokoro', 'business_district', 'FC', 'Abuja', 9.0400, 7.5300, array[]::text[]),
  ('Jabi', 'jabi', 'other', 'FC', 'Abuja', 9.0640, 7.4270, array[]::text[]),
  ('Utako', 'utako', 'other', 'FC', 'Abuja', 9.0670, 7.4400, array[]::text[]),
  ('Gwarinpa', 'gwarinpa', 'other', 'FC', 'Abuja', 9.1100, 7.4000, array['Gwarimpa']),
  ('Kubwa', 'kubwa', 'other', 'FC', 'Abuja', 9.1600, 7.3300, array[]::text[]),
  ('Lugbe', 'lugbe', 'other', 'FC', 'Abuja', 8.9700, 7.3700, array[]::text[]),
  ('Apo', 'apo', 'other', 'FC', 'Abuja', 8.9900, 7.4900, array['Apo Legislative Quarters']),
  ('Jabi Lake Mall', 'jabi-lake-mall', 'mall', 'FC', 'Abuja', 9.0710, 7.4240, array['Jabi Mall']),
  ('Ceddi Plaza', 'ceddi-plaza', 'mall', 'FC', 'Abuja', 9.0530, 7.4830, array[]::text[]),
  ('Silverbird Entertainment Centre', 'silverbird-entertainment-centre', 'mall', 'FC', 'Abuja', 9.0590, 7.4880, array['Silverbird Abuja']),
  ('Wuse Market', 'wuse-market', 'market', 'FC', 'Abuja', 9.0640, 7.4640, array['Wuse Zone 4 market']),
  ('Moshood Abiola National Stadium', 'moshood-abiola-national-stadium', 'stadium', 'FC', 'Abuja', 9.0007, 7.4170, array['National Stadium Abuja', 'Abuja stadium']),
  ('Eagle Square', 'eagle-square', 'other', 'FC', 'Abuja', 9.0523, 7.4882, array[]::text[]),
  ('Millennium Park', 'millennium-park', 'park', 'FC', 'Abuja', 9.0790, 7.4980, array[]::text[]),
  ('Aso Rock', 'aso-rock', 'other', 'FC', 'Abuja', 9.0850, 7.5170, array['Aso Villa']),
  ('Transcorp Hilton Abuja', 'transcorp-hilton-abuja', 'other', 'FC', 'Abuja', 9.0790, 7.4950, array['Transcorp', 'Hilton Abuja']),
  ('National Mosque', 'national-mosque', 'worship', 'FC', 'Abuja', 9.0570, 7.4920, array['Abuja National Mosque']),
  ('National Christian Centre', 'national-christian-centre', 'worship', 'FC', 'Abuja', 9.0510, 7.4980, array['Ecumenical Centre']),
  ('National Hospital Abuja', 'national-hospital-abuja', 'hospital', 'FC', 'Abuja', 9.0330, 7.4820, array['National Hospital']),
  ('Jabi Motor Park', 'jabi-motor-park', 'transport', 'FC', 'Abuja', 9.0580, 7.4200, array['Jabi park']),
  ('Idu Railway Station', 'idu-railway-station', 'transport', 'FC', 'Abuja', 9.0397, 7.3620, array['Idu station', 'Abuja train station'])
on conflict (slug) do update
  set name      = excluded.name,
      kind      = excluded.kind,
      city      = excluded.city,
      latitude  = excluded.latitude,
      longitude = excluded.longitude,
      aliases   = excluded.aliases;
