import { formatDate, formatMoney } from "@naijafinds/i18n";

/**
 * The RentMe transactional email shell.
 *
 * This is the same visual language as the Supabase auth templates generated by
 * scripts/build-auth-emails.mjs: deep navy-black canvas, dark card, electric
 * blue glow hairline, gradient call to action, the lockup at the top and
 * "RentMe. Find it. Rent it. Love it." at the bottom. The colours are the
 * sampled brand anchors and nothing here drifts toward purple.
 *
 * Email client reality drives every choice, exactly as it does in the
 * generator: table layout, fully inline styles, no external stylesheet, no web
 * fonts (system stack only), and a bulletproof button whose gradient degrades
 * to solid brand blue where background images are dropped.
 *
 * The difference from the generator is where links and images point. Auth
 * templates carry Supabase's own placeholders ({{ .SiteURL }}, {{ .Email }})
 * because Supabase renders them. These emails are rendered by us, so every URL
 * is absolute at render time, resolved from NEXT_PUBLIC_SITE_URL.
 *
 * Everything interpolated into a template goes through escapeHtml first:
 * listing titles, names and references come from the database or a form, and a
 * stray angle bracket must never be able to reshape the markup.
 */

// Brand constants, copied from the generator so the two stay identical.
const BASE = "#010118";
const CARD = "#030327";
const EDGE = "#101A55";
const PANEL = "#060640";
const GLOW = "#0C39EF";
const ELECTRIC = "#0010D0";
const TEXT = "#FFFFFF";
const BODY = "#C6CDF2";
const MUTED = "#7C86C2";
const GRADIENT = "linear-gradient(135deg," + GLOW + " 0%,#0621E8 55%," + ELECTRIC + " 100%)";
const FONT_SANS =
  "-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif";

/** The site the emails link back to. Absolute, no trailing slash. */
const DEFAULT_SITE_URL = "https://rentme.ng";

export function siteUrl(): string {
  const configured = (process.env.NEXT_PUBLIC_SITE_URL ?? "").trim();
  const base = configured.length > 0 ? configured : DEFAULT_SITE_URL;
  return base.replace(/\/+$/, "");
}

/** An absolute URL for an in-app path such as "/bookings". */
export function appUrl(path: string): string {
  return siteUrl() + (path.startsWith("/") ? path : "/" + path);
}

/** Escape text for HTML. Every interpolated value passes through here. */
export function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

/**
 * Money for humans. Integer kobo in, naira out, always through formatMoney so
 * a raw minor-unit integer can never reach a reader. formatMoney renders whole
 * naira; when an amount carries kobo they are appended, so a receipt stays
 * exact to the last kobo rather than quietly rounding.
 */
export function money(minor: number): string {
  const abs = Math.abs(Math.trunc(minor));
  const kobo = abs % 100;
  const whole = formatMoney(abs - kobo);
  const signed = minor < 0 ? "-" + whole : whole;
  if (kobo === 0) return signed;
  return signed + "." + String(kobo).padStart(2, "0");
}

/** An ISO date (YYYY-MM-DD) as "3 Aug 2026". Read at midday UTC so the
 * calendar day never slips a day either side of the date line. */
export function prettyDate(isoDate: string): string {
  const parsed = new Date(isoDate + "T12:00:00Z");
  if (Number.isNaN(parsed.getTime())) return isoDate;
  return formatDate(parsed);
}

/** "3 Aug 2026 to 7 Aug 2026", the one date phrase every stay email uses. */
export function dateRange(checkIn: string, checkOut: string): string {
  return prettyDate(checkIn) + " to " + prettyDate(checkOut);
}

/* --------------------------------------------------------------- fragments */

export function heading(text: string): string {
  return `<h1 style="margin:0 0 14px;font-size:24px;line-height:1.25;font-weight:700;letter-spacing:-0.02em;color:${TEXT};">${escapeHtml(text)}</h1>`;
}

/** A body paragraph. Pass safe markup only through `html`. */
export function paragraph(text: string): string {
  return `<p style="margin:0 0 18px;font-size:15px;line-height:1.6;color:${BODY};">${escapeHtml(text)}</p>`;
}

/** Bulletproof CTA. Gradient background image over a solid brand blue fallback. */
export function button(label: string, href: string): string {
  return `<table role="presentation" cellpadding="0" cellspacing="0" style="margin:8px 0 4px;">
                  <tr>
                    <td align="center" style="border-radius:12px;background-color:${GLOW};background-image:${GRADIENT};">
                      <a href="${escapeHtml(href)}" target="_blank" style="display:inline-block;padding:14px 30px;font-family:${FONT_SANS};font-size:15px;font-weight:600;color:${TEXT};text-decoration:none;border-radius:12px;">${escapeHtml(label)}</a>
                    </td>
                  </tr>
                </table>`;
}

export type ReceiptRow = {
  label: string;
  value: string;
  /** Emphasise this row: the total line of a receipt, or a new balance. */
  strong?: boolean;
};

/**
 * A key and value panel: what was booked, which dates, what it comes to. Two
 * columns in one table, because email clients cannot be trusted with anything
 * cleverer. Money values arrive already through money().
 */
export function receipt(rows: readonly ReceiptRow[]): string {
  const cells = rows
    .map((row, index) => {
      const top = index === 0 ? "0" : "1px solid " + EDGE;
      const valueColour = row.strong ? TEXT : BODY;
      const valueWeight = row.strong ? "700" : "500";
      return `<tr>
                    <td style="padding:10px 0;border-top:${top};font-size:13px;line-height:1.5;color:${MUTED};">${escapeHtml(row.label)}</td>
                    <td align="right" style="padding:10px 0;border-top:${top};font-size:14px;line-height:1.5;font-weight:${valueWeight};color:${valueColour};">${escapeHtml(row.value)}</td>
                  </tr>`;
    })
    .join("\n                  ");

  // The panel's padding lives on a cell, not on the table: Outlook drops
  // padding declared on a table element, which would push the rows flush
  // against the border.
  return `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="width:100%;margin:0 0 22px;">
                  <tr>
                    <td style="background:${PANEL};border:1px solid ${EDGE};border-radius:14px;padding:6px 18px;">
                      <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="width:100%;">
                        ${cells}
                      </table>
                    </td>
                  </tr>
                </table>`;
}

/** A single boxed reference, for a support ticket number. */
export function referenceBox(reference: string): string {
  return `<table role="presentation" cellpadding="0" cellspacing="0" style="margin:0 0 22px;">
                  <tr>
                    <td style="background:${PANEL};border:1px solid ${EDGE};border-radius:10px;padding:12px 20px;font-family:'SFMono-Regular',Consolas,monospace;font-size:18px;font-weight:700;letter-spacing:0.12em;color:${TEXT};">${escapeHtml(reference)}</td>
                  </tr>
                </table>`;
}

/** Muted small print inside the card, under the button. */
export function note(text: string): string {
  return `<p style="margin:18px 0 0;font-size:12px;line-height:1.6;color:${MUTED};">${escapeHtml(text)}</p>`;
}

/* ------------------------------------------------------------------- shell */

export type ShellOptions = {
  /** The inbox preview line. Never rendered in the body. */
  preheader: string;
  /** The card's middle: heading, paragraphs, receipt, button, notes. */
  body: string;
  /** Muted footer lines above the sign-off. Plain text, escaped here. */
  footerLines?: readonly string[];
};

const SIGN_OFF = "RentMe. Find it. Rent it. Love it.";

/**
 * Wrap a body in the branded shell. The markup mirrors the generator's shell
 * one element at a time, with the logo resolved to an absolute URL and the
 * account-action footer line replaced by whatever the message needs to say.
 */
export function shell(options: ShellOptions): string {
  const footer = (options.footerLines ?? [])
    .map(
      (line) =>
        `<p style="margin:0 0 6px;font-size:12px;line-height:18px;color:${MUTED};">${escapeHtml(line)}</p>`,
    )
    .join("\n                ");

  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="color-scheme" content="dark" />
    <meta name="supported-color-schemes" content="dark" />
    <title>RentMe</title>
  </head>
  <body style="margin:0;padding:0;background:${BASE};color:${BODY};font-family:${FONT_SANS};">
    <span style="display:none!important;visibility:hidden;opacity:0;height:0;width:0;overflow:hidden;mso-hide:all;">${escapeHtml(options.preheader)}</span>
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:${BASE};">
      <tr>
        <td align="center" style="padding:32px 16px;">
          <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:520px;width:100%;">
            <!-- electric hairline, the glow edge -->
            <tr><td style="height:4px;line-height:4px;font-size:0;background-image:${GRADIENT};background-color:${GLOW};border-radius:20px 20px 0 0;">&nbsp;</td></tr>
            <tr>
              <td style="background:${CARD};border:1px solid ${EDGE};border-top:0;border-radius:0 0 20px 20px;padding:40px 40px 36px;">
                <!-- lockup -->
                <table role="presentation" cellpadding="0" cellspacing="0">
                  <tr>
                    <td style="vertical-align:middle;padding-right:12px;">
                      <img src="${siteUrl()}/brand/rentme-logo.png" width="40" height="40" alt="" style="display:block;width:40px;height:40px;border:0;" />
                    </td>
                    <td style="vertical-align:middle;">
                      <span style="font-size:22px;font-weight:700;letter-spacing:-0.02em;color:${GLOW};background-image:${GRADIENT};-webkit-background-clip:text;background-clip:text;-webkit-text-fill-color:transparent;">RentMe</span>
                    </td>
                  </tr>
                </table>
                <div style="height:28px;line-height:28px;font-size:0;">&nbsp;</div>
                ${options.body}
              </td>
            </tr>
            <!-- footer -->
            <tr>
              <td style="padding:24px 40px 8px;">
                ${footer}
                <p style="margin:0;font-size:12px;line-height:18px;color:${MUTED};">
                  ${SIGN_OFF}
                </p>
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  </body>
</html>
`;
}
