import type { SupabaseClient } from "@supabase/supabase-js";

/**
 * `availability_checks` is not in the generated database types yet, for the
 * reason `lib/price-check/rpc.ts` gives (the generated file is shared and is
 * regenerated by whoever owns it). One untyped door, here, rather than casts
 * sprinkled through the callers; the columns read are named at each call.
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function availabilityTable(db: unknown): ReturnType<SupabaseClient<any>["from"]> {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  return (db as SupabaseClient<any>).from("availability_checks");
}
