import { matchRoute } from "./resolve";

/**
 * What a screen is CALLED, for the back control's accessible name.
 *
 * A back control that says only "Back" makes a screen-reader user press it to
 * find out where it goes. "Back to Messages" says it before the press, which
 * is what the platform's own navigation bars do. Keyed by the same patterns as
 * `route-parents.ts`, so a dynamic screen is named for what it is ("the
 * listing") rather than for its id.
 *
 * ENGLISH ONLY, ON PURPOSE. These names are composed into "Back to <name>" for
 * an English reader. Every other locale keeps the translated `common.back`
 * word, because a Yoruba, Hausa or Igbo reader is better served by one word in
 * their language than by a sentence in someone else's. `BackControl` makes
 * that choice; `resolve.test.ts` checks every declared parent has a name here.
 *
 * A pattern with no name answers `null`, and the control says "Back".
 */
const NAMES: Readonly<Record<string, string>> = {
  "/": "Vallo",
  "/about": "About",
  "/docs": "the guide",
  "/docs/[slug]": "the chapter",
  "/r": "referrals",
  "/sign-in": "sign in",
  "/sign-in/email": "sign in",
  "/sign-up": "sign up",
  "/sign-up/email": "sign up",
  "/sign-up/finish": "finishing sign up",
  "/forgot-password": "password reset",
  "/welcome": "the welcome",
  "/home": "Home",
  "/home-or-landing": "Home",
  "/stays": "Stays",
  "/search": "Search",
  "/listing/[id]": "the listing",
  "/listing/[id]/trust": "why to trust this space",
  "/saved": "Saved",
  "/saved/searches": "saved searches",
  "/record/[code]": "the record",
  "/tenancy/[id]": "the tenancy",
  "/price": "Price check",
  "/price/area/[id]": "the area price",
  "/stays/search": "stay search",
  "/stay/[id]": "the stay",
  "/restaurants": "Restaurants",
  "/restaurant/[id]": "the restaurant",
  "/bookings": "Plans",
  "/bookings/[bookingId]": "the booking",
  "/messages": "Messages",
  "/messages/[id]": "the conversation",
  "/agreements": "Agreements",
  "/agreements/[id]": "the agreement",
  "/agreements/[id]/fund": "Pay the rent",
  "/agreements/[id]/held": "Escrow payment",
  "/payments": "Payments",
  "/receipts": "Receipts",
  "/refunds": "Refunds",
  "/payouts": "Payouts",
  "/wallet": "Balance",
  "/around": "Around",
  "/around/[slug]": "the district",
  "/around/settings": "feed settings",
  "/around/people": "find people",
  "/post/[id]": "the post",
  "/stories/[id]": "the story",
  "/u": "people",
  "/u/[handle]": "the profile",
  "/u/[handle]/followers": "followers",
  "/u/[handle]/following": "following",
  "/assistant": "the assistant",
  "/notifications": "Notifications",
  "/notifications/[id]": "the notification",
  "/profile": "Profile",
  "/profile/application": "your application",
  "/profile/setup": "profile setup",
  "/settings": "Settings",
  "/settings/account": "Account",
  "/settings/devices": "Devices",
  "/settings/help": "Help",
  "/settings/privacy": "Privacy",
  "/settings/notifications": "Notifications settings",
  "/settings/payments": "Payment settings",
  "/support": "Help and support",
  "/support/messages": "your tickets",
  "/support/messages/[id]": "the ticket",
  "/legal/privacy": "the privacy policy",
  "/legal/terms": "the terms",
  "/admin": "the console",
  "/admin/bookings": "Bookings",
  "/admin/bookings/[bookingId]": "the booking",
  "/admin/handbook": "the handbook",
  "/admin/kyc": "KYC",
  "/admin/listings": "Listings",
  "/admin/listings/[id]": "the listing",
  "/admin/operations": "Operations",
  "/admin/people": "People",
  "/admin/people/[id]": "the person",
  "/admin/queue": "the queue",
  "/admin/support": "Support",
  "/admin/money": "Money",
  "/agent/dashboard": "the dashboard",
  "/agent/listings": "Listings",
  "/agent/analytics/[metric]": "the figure",
  "/agent/analytics/listings/[listingId]": "the listing's week",
  "/agent/listings/[listingId]/health": "listing health",
  "/agent/messages": "Messages",
  "/agent/messages/[id]": "the conversation",
  "/agent/bookings": "Bookings",
  "/agent/inspections": "Inspections",
  "/agent/notifications": "Notifications",
  "/agent/settings": "Settings",
  "/host": "the host workspace",
  "/host/reservations": "Reservations",
  "/host/bookings": "Room bookings",
  "/host/rooms": "Rooms",
  "/host/calendar": "Calendar",
  "/host/earnings/statement": "the statement",
  "/host/decide": "Decide by",
  "/host/reviews": "Reviews",
  "/host/settings": "Settings",
  "/host/notifications": "Notifications",
  "/areas/[state]/[area]": "the area",
  "/cancellations": "Cancellations",
  "/careers": "Careers",
  "/contact": "Contact",
  "/delete-account": "Delete account",
  "/eula": "the licence",
  "/help": "Help",
  "/r/[code]": "the invitation",
  "/privacy": "Privacy",
  "/disclaimer": "the disclaimer",
  "/safety": "Safety",
  "/check": "the check",
  /* Recommendations A: the public doors. */
  "/for-agents": "For agents",
  "/for-hosts": "For hosts",
  "/for-landlords": "For landlords",
  "/move-in-cost": "the calculator",
  "/guides": "Guides",
  "/guides/[slug]": "the guide",
  "/email/preferences": "Email preferences",
  "/join/[code]": "the invite",
  "/sign-in/code": "Sign in with a code",
  "/sign-in/phone": "Sign in with your phone",
  "/standards": "Standards",
  "/styleguide": "the style guide",
  "/terms": "Terms",
  "/inspections/gate/[id]": "the gate code",
  "/rent/share/[id]": "the rent share",
  "/settings/passport": "your passport",
  "/settings/invite": "your invite link",
  "/settings/invite/how-it-works": "how invites work",
  "/settings/invite/referrals": "who joined with your code",
  "/settings/invite/referrals/[id]": "this referral",
  "/rewards": "your rewards",
  "/pro": "Vallo Pro",
  "/rewards/referrals": "your referrals",
  "/rewards/history": "your rewards history",
  "/rewards/withdraw": "withdrawing",
  "/leaderboard": "the leaderboard",
  "/directory": "the directory",
  "/settings/passport/[fact]": "this part of your passport",
  "/around/manage": "your places",
  "/u/[handle]/edit": "your profile",
  "/settings/appearance": "Appearance",
  "/settings/accessibility": "Accessibility",
  "/settings/region": "Language and currency",
  "/settings/devices/alert": "the sign-in alert",
  "/settings/interests": "Interests",
  "/settings/place": "Your place",
  "/settings/privacy/blocked": "Blocked people",
  "/settings/privacy/money-lock": "Money lock",
  "/settings/privacy/ai": "Assistant agreement",
  "/settings/privacy/data": "Your data",
  "/legal/disclaimer": "the disclaimer",
  "/admin/agents": "Agents",
  "/admin/alerts": "Alerts",
  "/admin/analytics": "Analytics",
  "/admin/front-door": "Front door",
  "/admin/audit": "Audit",
  "/admin/lookup": "Lookup",
  "/admin/oversight": "Oversight",
  "/admin/bookings/reservations": "Reservations",
  "/admin/businesses": "Businesses",
  "/admin/agreements": "Agreements",
  "/admin/agreements/settings": "Risk settings",
  "/admin/staff": "Staff",
  "/admin/fees": "Fees",
  "/admin/compliance": "Compliance",
  "/admin/payments": "Payments",
  "/admin/reference": "Reference",
  "/admin/settings": "Settings",
  "/admin/social": "Social",
  "/admin/standing": "Standing",
  "/admin/supply": "Supply",
  "/admin/switches": "Switches",
  "/agent/analytics": "Analytics",
  "/agent/earnings": "Earnings",
  "/agent/listings/[listingId]/calendar": "the calendar",
  "/agent/listings/[listingId]/board": "the board",
  "/agent/listings/[listingId]/status": "the status kit",
  "/agent/listings/[listingId]/promotion": "promotion results",
  "/agent/promotion": "Promote your listings",
  "/agent/reviews": "Reviews",
  "/agent/portfolio": "Portfolio",
  "/agent/verification": "Verification",
  "/agent/firm": "the firm",
  "/agent/assistant": "the assistant",
  "/host/earnings": "Earnings",
  "/host/photos": "Photos",
  "/host/assistant": "the assistant",
  "/host/arrival": "the arrival guide",
  "/agent/listings/[listingId]/arrival": "the arrival guide",
  "/admin/examples": "Examples",
  "/admin/handbook/position": "the position",
  "/admin/account-recovery": "Account recovery",
  "/admin/field-speed": "Field speed",
  "/admin/stops": "Stops",
  "/preview": "the previews",
  "/preview/[deck]": "the deck",
  "/preview/[deck]/[screen]": "the screen",
};

/** The English name of the screen at `path`, or `null` when it has none. */
export function screenName(path: string): string | null {
  const matched = matchRoute(path);
  if (!matched) return null;
  return NAMES[matched.pattern] ?? null;
}

/** "Back to Messages", or `null` when the destination has no name. */
export function backToLabel(path: string): string | null {
  const name = screenName(path);
  return name ? `Back to ${name}` : null;
}
