import type { UiIconName } from "./UiIcon";
import type { BrandIconObject } from "./BrandIcon";

/**
 * THE DAYLIGHT TWIN OF EVERY GLASS OBJECT, AS A LINE GLYPH.
 *
 * The founder, 29 September 2026, on a live light-mode profile: the glass
 * objects on white "are pale blue blobs with fuzzy inner glyphs". The artwork
 * was drawn for a night ground, and no amount of drop shadow and edge fade
 * makes it read on paper. So in the light theme, outside a night island,
 * `BrandIcon` draws a solid brand-blue rounded tile with the matching crisp
 * `UiIcon` in white instead (`app/css/light.css`, "THE GLASS OBJECTS IN
 * DAYLIGHT"). Inside a night island (`data-theme="dark"`: the header, the
 * drawer, the rail, the profile hero) the glass stays, because there it is
 * on the ground it was drawn for.
 *
 * Every object has an entry, so the type fails the build when an object is
 * added to the pack without a daylight answer. The mapping is by MEANING, not
 * by silhouette: every house type is `house` unless a specific house glyph
 * exists, every money object is `wallet`, every document is `document`.
 */
export const FLAT_FOR: Record<BrandIconObject, UiIconName> = {
  "alert-triangle": "info",
  "apartment-block": "building-apartment",
  "bank-column": "wallet",
  "beach-house": "house",
  "bed-ring": "bed",
  "bell-badge": "bell",
  "bell-tile": "bell",
  "bill-tile": "document",
  "booking-instant": "bolt",
  "bookmark-ribbon": "bookmark",
  bot: "sparkle",
  "brain-chip": "sparkle",
  "brain-ring": "sparkle",
  "building-chip": "building-apartment",
  bungalow: "house-bungalow",
  "calendar-check": "calendar-booking",
  "calendar-clock": "calendar-booking",
  "calendar-grid": "calendar-booking",
  "calendar-home": "calendar-booking",
  "calendar-ring": "calendar-booking",
  "calendar-time": "calendar-booking",
  camera: "picture",
  "card-lock": "wallet",
  "card-tile": "wallet",
  "chart-growth": "views",
  "chart-ring": "views",
  "chat-duo": "chat-bubble",
  "chat-ring": "chat-bubble",
  "city-ring": "building-apartment",
  "clock-check": "history",
  "clock-expired": "history",
  "cluster-home": "house",
  "coin-naira": "wallet",
  "concierge-bell": "bell",
  "container-home": "house",
  "contract-sign": "document",
  "coworking-space": "briefcase",
  "doc-cross": "document",
  "doc-home": "document",
  "doc-lock": "document",
  "doc-review": "document",
  "doc-shield": "document",
  duplex: "house-duplex",
  "farm-house": "house",
  "flip-coin": "switch-profile",
  gift: "star",
  "gift-star": "star",
  globe: "compass",
  "globe-chip": "compass",
  "globe-pin": "location",
  "guest-house": "house",
  headset: "chat-bubble",
  "heart-home": "heart",
  "home-check": "home",
  "home-lock": "home",
  "home-ring": "home",
  "home-search": "search",
  hotel: "building-hotel",
  "hotel-bed": "bed",
  "hotel-room": "bed",
  "hotel-star": "building-hotel",
  hourglass: "history",
  "house-boat": "house",
  "id-card-check": "user",
  info: "info",
  "inspect-ring": "eye",
  "key-cycle": "key",
  "key-ring": "key",
  "keys-handover": "key",
  "keys-home": "key",
  "keys-tag": "key",
  "lake-house": "house",
  "land-plot": "land-plot",
  "ledger-book": "document",
  "listing-search": "search",
  loft: "house",
  "luggage-check": "briefcase",
  "luggage-plane": "briefcase",
  "manage-ring": "sliders",
  mansion: "house",
  "map-route": "map",
  "map-spot": "location",
  "mini-flat": "building-apartment",
  "modern-house": "house",
  "mountain-cabin": "house",
  "naira-coins": "wallet",
  "naira-hand": "wallet",
  "office-space": "briefcase",
  palette: "contrast",
  "palm-tree": "sun",
  "payment-failed": "wallet",
  "payment-received": "wallet",
  "payment-sent": "wallet",
  penthouse: "tower-penthouse",
  "people-ring": "user",
  "person-card": "user",
  "phone-tile": "phone",
  "pin-map": "location",
  "progress-ring": "history",
  "receipt-check": "document",
  "report-stats": "views",
  reviews: "star",
  "role-switch-tile": "switch-profile",
  "savings-pot": "wallet",
  "seal-check": "verified",
  "seal-cross": "block",
  "seal-pending": "history",
  "search-home": "search",
  "search-ring": "search",
  "send-plane-tile": "share",
  "serviced-apartment": "building-apartment",
  "serviced-block": "building-apartment",
  "shared-apartment": "building-apartment",
  "shield-check": "verified",
  "shield-check-tile": "verified",
  "shield-home": "verified",
  "shield-lock": "verified",
  "shield-ring": "verified",
  "shop-retail": "storefront",
  shortlet: "bed",
  "stays-hotel-palms": "building-hotel",
  "studio-apartment": "building-apartment",
  "support-chat": "chat-bubble",
  "support-shield": "verified",
  "tag-hash": "price-tag",
  "tag-percent": "price-tag",
  "terrace-house": "house-terrace",
  "tour-360": "eye",
  townhouse: "house-terrace",
  "transfer-arrow": "switch-profile",
  "tree-house": "house",
  "twin-house": "house-duplex",
  "user-check": "user",
  "user-verified": "user",
  villa: "house",
  wallet: "wallet",
  "wallet-chip": "wallet",
  "wallet-naira": "wallet",
  "wallet-out": "wallet",
  "wallet-plus": "wallet",
  "wallet-ring": "wallet",
  "wallet-secure": "wallet",
  "wallet-tile": "wallet",
  warehouse: "storefront",
};

/**
 * The glyph edge for a flat tile drawn in a box of `size` pixels, snapped by
 * `UiIcon` itself. Below 28px there is no room for a tile and a glyph with a
 * margin, so the glyph is drawn bare in brand blue (`data-bare`).
 */
export function flatGlyphSize(size: number): number {
  return Math.max(12, Math.round(size * 0.44));
}
export const FLAT_BARE_BELOW = 28;
