import type { BrandIconName } from "./BrandIcon";
import type { UiIconName } from "./UiIcon";

/**
 * THE GLASS OBJECTS' LINE TWINS (the icon upgrade, 29 September 2026).
 *
 * The founder's references draw one family: a lean line glyph on a soft flat
 * plate (`docs/design/CLEAN_UNIFIED_DIRECTION.md` section 4; the lead's Q3:
 * the glass objects retire from light mode and the landing's feature cards
 * take the flat plate too). A component that still takes a `BrandIconName`
 * (the `State` kit, the empty states, a data table of objects) draws the
 * object's line twin from this table on an `IconPlate`, so a call site does
 * not have to change for the platform to read as one set.
 *
 * Every object has a twin, chosen for what the object MEANS on the screens
 * that use it, not for what it depicts: `naira-hand` is money paid out, so
 * `hand-coins`; `doc-review` is "under review", so `file-search`. Where the
 * set has no drawing the nearest meaning stands in and the entry says so.
 * The seven legacy aliases are listed as well, so the table covers every
 * name a call site may pass.
 */
export const GLASS_TO_LINE: Record<BrandIconName, UiIconName> = {
  "alert-triangle": "alert-triangle",
  "apartment-block": "building-apartment",
  "bank-column": "bank",
  "beach-house": "house",
  "bed-ring": "bed",
  "bell-badge": "bell",
  "bell-tile": "bell",
  "bill-tile": "receipt",
  "booking-instant": "bolt",
  "bookmark-ribbon": "bookmark",
  bot: "bot",
  "brain-chip": "sparkle",
  "brain-ring": "sparkle",
  "building-chip": "building-apartment",
  bungalow: "house-bungalow",
  "calendar-check": "calendar-check",
  "calendar-clock": "calendar-clock",
  "calendar-grid": "calendar-booking",
  "calendar-home": "calendar-booking",
  "calendar-ring": "calendar-booking",
  "calendar-time": "calendar-clock",
  camera: "camera",
  "card-lock": "credit-card",
  "card-tile": "credit-card",
  "chart-growth": "trending-up",
  "chart-ring": "chart-bar",
  "chat-duo": "messages",
  "chat-ring": "chat-bubble",
  "city-ring": "building-apartment",
  "clock-check": "clock",
  "clock-expired": "hourglass",
  "cluster-home": "home",
  "coin-naira": "coins",
  "concierge-bell": "concierge-bell",
  "container-home": "house",
  "contract-sign": "file-text",
  "coworking-space": "briefcase",
  "doc-cross": "circle-x",
  "doc-home": "file-text",
  "doc-lock": "lock",
  "doc-review": "file-search",
  "doc-shield": "file-check",
  duplex: "house-duplex",
  "farm-house": "house",
  "flip-coin": "coins",
  gift: "sparkle",
  "gift-star": "star",
  globe: "globe",
  "globe-chip": "globe",
  "globe-pin": "location",
  "guest-house": "house",
  headset: "headset",
  "heart-home": "heart",
  "home-check": "home",
  "home-lock": "lock",
  "home-ring": "home",
  "home-search": "search",
  hotel: "building-hotel",
  "hotel-bed": "bed",
  "hotel-room": "bed",
  "hotel-star": "building-hotel",
  hourglass: "hourglass",
  "house-boat": "house",
  "id-card-check": "id-card",
  info: "info",
  "inspect-ring": "search",
  "key-cycle": "key",
  "key-ring": "key",
  "keys-handover": "key",
  "keys-home": "key",
  "keys-tag": "price-tag",
  "lake-house": "house",
  "land-plot": "land-plot",
  "ledger-book": "file-text",
  "listing-search": "search",
  loft: "building-apartment",
  "luggage-check": "circle-check",
  "luggage-plane": "ticket",
  "manage-ring": "sliders",
  mansion: "house",
  "map-route": "map",
  "map-spot": "location",
  "mini-flat": "building-apartment",
  "modern-house": "house",
  "mountain-cabin": "house",
  "naira-coins": "coins",
  "naira-hand": "hand-coins",
  "office-space": "briefcase",
  palette: "contrast",
  "palm-tree": "sun",
  "payment-failed": "circle-x",
  "payment-received": "hand-coins",
  "payment-sent": "banknote",
  penthouse: "tower-penthouse",
  "people-ring": "users",
  "person-card": "id-card",
  "phone-tile": "phone",
  "pin-map": "location",
  "progress-ring": "circle-play",
  "receipt-check": "receipt",
  "report-stats": "chart-bar",
  reviews: "star",
  "role-switch-tile": "switch-profile",
  "savings-pot": "wallet",
  "seal-check": "circle-check",
  "seal-cross": "circle-x",
  "seal-pending": "hourglass",
  "search-home": "search",
  "search-ring": "search",
  "send-plane-tile": "share",
  "serviced-apartment": "building-apartment",
  "serviced-block": "building-apartment",
  "shared-apartment": "users",
  "shield-check": "shield-check",
  "shield-check-tile": "shield-check",
  "shield-home": "shield-check",
  "shield-lock": "shield-lock",
  "shield-ring": "shield-check",
  "shop-retail": "storefront",
  shortlet: "building-hotel",
  "stays-hotel-palms": "building-hotel",
  "studio-apartment": "building-apartment",
  "support-chat": "headset",
  "support-shield": "headset",
  "tag-hash": "price-tag",
  "tag-percent": "price-tag",
  "terrace-house": "house-terrace",
  "tour-360": "eye",
  townhouse: "house-terrace",
  "transfer-arrow": "switch-profile",
  "tree-house": "house",
  "twin-house": "house-duplex",
  "user-check": "user-check",
  "user-verified": "user-check",
  villa: "house",
  wallet: "wallet",
  "wallet-chip": "wallet",
  "wallet-naira": "wallet",
  "wallet-out": "wallet",
  "wallet-plus": "wallet",
  "wallet-ring": "wallet",
  "wallet-secure": "wallet",
  "wallet-tile": "wallet",
  warehouse: "storefront",
  /* The seven legacy aliases. */
  "bell-alert": "bell",
  chat: "chat-bubble",
  "bot-chat": "bot",
  "bot-home": "bot",
  "listing-review": "file-search",
  "homes-sparkle": "home",
  "house-sparkle": "house",
};

/** The line twin of a glass object. */
export function lineGlyphFor(name: BrandIconName): UiIconName {
  return GLASS_TO_LINE[name];
}
