import "server-only";

import type { SupabaseClient } from "@supabase/supabase-js";

import { createClient } from "../supabase/server";
import type {
  AccommodationPhotoRow,
  AccommodationRow,
  BusinessRow,
  CancellationPolicyRow,
  CatalogueEntityKind,
  CatalogueEntryRow,
  LandmarkHit,
  RatePlanRow,
  RestaurantProfileRow,
  RoomCategory,
  RoomTypeRow,
  ServiceWindowRow,
  StaySearchRow,
} from "./types";

/**
 * The stays tables as this module types them.
 *
 * The generated `Database` type in lib/supabase is regenerated by the lead
 * when a phase closes, and until then it may or may not describe the M1 to M9
 * tables. Reads here must compile either way, so this file carries the small
 * schema they need and casts the request-scoped client to it once. The cast
 * is the only one in lib/stays; every query below it is typed.
 */

type Table<Row> = {
  Row: Row;
  Insert: Record<string, never>;
  Update: Record<string, never>;
  Relationships: [];
};

export type StaysSearchArgs = {
  p_entity_kinds?: CatalogueEntityKind[];
  p_q?: string;
  p_state_code?: string;
  p_city?: string;
  p_area?: string;
  p_check_in?: string;
  p_check_out?: string;
  p_rooms?: number;
  p_guests?: number;
  p_min_price_minor?: number;
  p_max_price_minor?: number;
  p_min_rating?: number;
  p_room_categories?: RoomCategory[];
  p_amenities?: string[];
  p_breakfast?: boolean;
  p_free_cancellation?: boolean;
  p_verified?: boolean;
  p_lat?: number;
  p_lng?: number;
  p_radius_m?: number;
  p_sort?: string;
  p_limit?: number;
  p_offset?: number;
};

export type StaysDatabase = {
  public: {
    Tables: {
      accommodations: Table<AccommodationRow>;
      accommodation_photos: Table<AccommodationPhotoRow>;
      accommodation_amenities: Table<{ accommodation_id: string; amenity_id: string }>;
      amenities: Table<{ id: string; code: string; label: string; category: string }>;
      businesses: Table<BusinessRow>;
      cancellation_policies: Table<CancellationPolicyRow>;
      catalogue_entries: Table<CatalogueEntryRow>;
      rate_plans: Table<RatePlanRow>;
      restaurant_profiles: Table<RestaurantProfileRow>;
      room_types: Table<RoomTypeRow>;
      service_windows: Table<ServiceWindowRow>;
    };
    Views: Record<string, never>;
    Functions: {
      stays_search: { Args: StaysSearchArgs; Returns: StaySearchRow[] };
      landmarks_resolve: {
        Args: { p_term: string; p_state?: string; p_limit?: number };
        Returns: LandmarkHit[];
      };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};

export type StaysClient = SupabaseClient<StaysDatabase>;

/** The request-scoped, RLS-bound client, typed for the stays tables. */
export async function staysClient(): Promise<StaysClient> {
  const supabase = await createClient();
  return supabase as unknown as StaysClient;
}
