"use server";

/**
 * Booking checkout: the two ways a guest actually pays.
 *
 * Reserve inserts a PENDING booking and holds the calendar. Until this file
 * existed nothing could move money against it, so a stay could be requested
 * and never paid for. Both paths here close that loop, and both refuse rather
 * than pretend when the platform is not configured yet.
 *
 *  - startCardCheckout writes a PENDING `transactions` row whose provider_ref
 *    is a fresh `rm-book-<uuid>` reference, then opens a hosted Paystack
 *    checkout for the amount on the STORED booking row. Settlement belongs to
 *    the webhook and the return path, never to this action: nothing here marks
 *    anything paid.
 *  - settleCardPayment is the return-from-Paystack path. It verifies with the
 *    processor and then calls the same settlement the webhook calls, so
 *    whichever arrives first wins and the second is a no-op.
 *
 * VALLO NEVER HOLDS THE MONEY (Track A, 25 September 2026). Payment opens only
 * on an approved agreement, and every charge carries the split the database
 * computed: the lister's share to their own subaccount, the Guarantee
 * contribution to the reserve subaccount, Vallo's commission (zero today) to
 * the main account, all from the same transaction. There is no wallet path:
 * a balance Vallo held would be custody. The amount is always the booking
 * total exactly as stored, never taken from the client.
 *
 * Every amount is integer kobo, end to end (Master Rule 50).
 */

import { createHash } from "node:crypto";
import { revalidatePath } from "next/cache";
import { headers } from "next/headers";
import { fail, ok, validate, type ActionResult } from "../actions/envelope";
import {
  NOT_CONFIGURED_MESSAGE,
  SIGNED_OUT_MESSAGE,
  resolveSession,
} from "../actions/session";
import { contactFromSession } from "../email/recipients";
import { isFeatureEnabled } from "../flags";
import {
  PaystackError,
  initializeTransaction,
  isPaystackConfigured,
  verifyTransaction,
} from "../payments/paystack";
import { chargeSavedCard, type ChargeSavedCardOutcome } from "../payments/charge-saved-card";
import { isBookingReference } from "../payments/references";
import { insertSplitAttempt, isRefusal, openSplitAttempt, quoteSplit } from "../payments/split-attempt";
import { bookingHasPaymentInFlight, recordCheckoutHandle, reuseLiveAttempt } from "../payments/attempts";
import { withBookingOpenLease } from "../payments/booking-lease";
import { refundChargeToCard } from "../payments/refund";
import { IN_FLIGHT_MESSAGE, withIdempotency, type IdempotentRun } from "../security/idempotency";
import { bookingPaymentSubject } from "./payment-subject";
import { checkoutReturnPath } from "../rent/return-path";
import { guardMoney } from "../security/money-limits";
import { getAdminClient } from "@/lib/supabase/service";
import { announceConfirmedStay } from "./arrival";
import { cancelInputSchema } from "./schema";
import { bookingForReference, markChargeFailed, settleBookingCharge } from "./settlement";
import type { Database } from "../supabase/database.types";

const PAUSED_MESSAGE =
  "Bookings are paused for maintenance. Please try again in a little while.";

const CARD_UNCONFIGURED_MESSAGE =
  "We cannot reach card payment right now. Your booking is untouched and your dates are still held.";

const NOT_FOUND_MESSAGE =
  "We could not find that booking on your account. Open it again from Bookings, and check you are signed in with the account that reserved it.";

/**
 * A reference that resolves to nothing is the one checkout error where the
 * reader's real question is "where is my money", so the copy answers that
 * before it asks them to do anything.
 */
const UNKNOWN_REFERENCE_MESSAGE =
  "That payment reference is not recognised. Open the stay from Bookings and start the payment again. If money has already left your account, contact support and we will trace it.";

const ALREADY_PAID_MESSAGE = "This booking is already paid, so there is nothing to pay again.";

const CANCELLED_MESSAGE =
  "This booking was cancelled, so it cannot be paid. Search again and pick new dates.";


const SERVICE_DOWN_MESSAGE =
  "Payment is temporarily unavailable. Your booking is unchanged. Please try again shortly.";

/* ------------------------------------------------------------------ shapes */

export type CheckoutInput = {
  bookingId: string;
  /**
   * One key per submit, generated by the surface. A dropped connection and a
   * second tap carry the same key, so the retry replays the first answer
   * instead of paying twice.
   */
  idempotencyKey?: string;
  /** V-81: a fresh proof for paying this booking from the wallet, when the person locked money with a phone. */
  stepUp?: string;
};

export type CardCheckout = {
  /** Where to send the guest to pay. */
  authorizationUrl: string;
  /**
   * The same transaction, addressed the other way.
   *
   * `authorizationUrl` is where to SEND somebody; this is the handle that
   * resumes the very same transaction in a checkout drawn on our own page,
   * which is what stops paying being a departure from Vallo. Paystack has
   * returned it on every initialise this platform has ever made
   * (`initializeTransaction` populates it) and until now nothing read it.
   *
   * IT DISCLOSES NOTHING NEW TO THE BROWSER. The hosted URL beside it is
   * literally `https://checkout.paystack.com/<access code>`: the code has
   * always been the last path segment of a URL we hand the browser and then
   * navigate it to. Returning it under its own name is a rename, not a leak.
   * It is a per-transaction handle, never a key, and it must not be confused
   * with the secret key, which is server-only and stays there.
   */
  accessCode: string;
  reference: string;
  amountMinor: number;
};

export type CardSettlement = {
  bookingId: string;
  amountMinor: number;
  /** True when this call moved the booking to CONFIRMED. */
  confirmed: boolean;
};

/** The booking row a payment path is allowed to act on. */
type PayableBooking = {
  id: string;
  listing_id: string;
  guest_id: string;
  status: Database["public"]["Enums"]["booking_status"];
  check_in: string;
  check_out: string;
  nights: number;
  total_minor: number;
  currency: string;
};

/** Where a hosted checkout sends the guest back to. */
async function siteOrigin(): Promise<string> {
  const explicit = process.env.NEXT_PUBLIC_SITE_URL ?? "";
  if (explicit.length > 0) return explicit.replace(/\/+$/, "");
  const h = await headers();
  const host = h.get("x-forwarded-host") ?? h.get("host");
  const proto = h.get("x-forwarded-proto") ?? "https";
  return host ? `${proto}://${host}` : "http://localhost:3000";
}

/** Keep a processor's own words, without ever surfacing a raw code. */
function describePaystackError(e: unknown, fallback: string): string {
  if (e instanceof PaystackError && e.status !== 401 && e.message.trim().length > 0) {
    return `${fallback} The payment service said: ${e.message.trim()}`;
  }
  return fallback;
}

/* --------------------------------------------------- one guard per booking */

/**
 * ONE SCOPE AND ONE SUBJECT FOR EVERY WAY OF PAYING A BOOKING.
 *
 * Each path used to open its own scope under the payer's user id with a key
 * the browser minted per attempt. That guards a double tap, and nothing else:
 * two attempts on one booking that carried two keys (a wallet tap and a card
 * tap racing, or two tabs) both passed `guardPayable`, because neither had
 * settled yet when the other read, and both charged. The lead's B0 audit of
 * 73e284e named it.
 *
 * The subject is now the BOOKING, and the three paths share one scope, so the
 * idempotency claim is "somebody is paying this booking right now" whichever
 * button was pressed. A second concurrent attempt on the same booking answers
 * IN_FLIGHT rather than charging; a retry after a genuine failure still runs,
 * because a failed answer is released rather than recorded (`shouldRecord`
 * stays `result.ok`) and a different key claims afresh once the first has let
 * go. The key is still the client's, so an honest replay of the same tap still
 * replays the first answer rather than paying twice.
 */
const BOOKING_PAYMENT_SCOPE = "booking.payment";


/* --------------------------------------------------------- shared guards */

type Guarded =
  /* `never` rather than `null`, so a refusal is returnable from a path whose
     success type is not nullable: the guard only ever puts a failure here. */
  | { ok: false; result: ActionResult<never> }
  | {
      ok: true;
      booking: PayableBooking;
      userId: string;
      email: string | null;
      displayName: string | null;
    };

/**
 * Prove the caller owns this booking and that it can still be paid.
 *
 * Ownership comes from reading through the caller's OWN RLS-bound client: a
 * booking that is not theirs simply does not come back, so the database is the
 * authority on identity rather than a check this code could forget. The amount
 * is read here and used everywhere after, so no payment path can be handed a
 * figure by a client.
 */
async function guardPayable(bookingId: string): Promise<Guarded> {
  const session = await resolveSession();
  if (session.state === "unconfigured") return { ok: false, result: fail<never>(NOT_CONFIGURED_MESSAGE) };
  if (session.state === "signed-out") return { ok: false, result: fail<never>(SIGNED_OUT_MESSAGE) };

  if (!(await isFeatureEnabled("bookings"))) return { ok: false, result: fail<never>(PAUSED_MESSAGE) };

  const parsed = validate(cancelInputSchema, { bookingId });
  if (!parsed.ok) return { ok: false, result: fail<never>(parsed.error, parsed.fieldErrors) };

  const { data: booking, error } = await session.supabase
    .from("bookings")
    .select("id, listing_id, guest_id, status, check_in, check_out, nights, total_minor, currency")
    .eq("id", parsed.data.bookingId)
    .maybeSingle();

  if (error) return { ok: false, result: fail<never>(SERVICE_DOWN_MESSAGE) };
  if (!booking) return { ok: false, result: fail<never>(NOT_FOUND_MESSAGE) };
  /* SEC-P2-04. Reading a booking is not owning it: the host and admins can
     read it too. Only its guest pays for it, as the wallet path already
     requires (pay_booking_from_wallet: guest_id = payer). */
  if (booking.guest_id !== session.user.id) return { ok: false, result: fail<never>(NOT_FOUND_MESSAGE) };
  if (booking.status === "CANCELLED") return { ok: false, result: fail<never>(CANCELLED_MESSAGE) };
  // CONFIRMED is deliberately payable. A request-to-book stay is confirmed by
  // the host accepting it, not by money arriving, so refusing CONFIRMED here
  // meant an accepted stay could never be paid on the platform at all: the
  // guest was told "nothing further is needed" while the host was never paid.
  // What decides whether there is anything left to pay is a settled payment
  // attempt, checked a few lines below, and that is the only honest test.
  if (booking.currency !== "NGN") {
    return {
      ok: false,
      result: fail(
        "This booking is not priced in naira, so it cannot be paid here. Contact support and we will sort it out with you.",
      ),
    };
  }
  if (booking.total_minor <= 0) {
    return {
      ok: false,
      result: fail("This booking has no amount to pay. Contact support and we will sort it out."),
    };
  }

  // A booking with a settled attempt is paid, whatever its status says. Reading
  // it through the caller's own client keeps this inside their own visibility.
  const { data: settled } = await session.supabase
    .from("transactions")
    .select("id")
    .eq("booking_id", booking.id)
    .eq("status", "SUCCESSFUL")
    .limit(1);
  if ((settled?.length ?? 0) > 0) return { ok: false, result: fail<never>(ALREADY_PAID_MESSAGE) };

  const metadataName = session.user.user_metadata["full_name"] as string | undefined;
  const name = (metadataName ?? "").trim();

  return {
    ok: true,
    booking: booking as PayableBooking,
    userId: session.user.id,
    email: session.user.email ?? null,
    displayName: name.length > 0 ? name : null,
  };
}

/* ------------------------------------------------------------ card path */

async function startCardCheckoutWork(
  booking: PayableBooking,
  userId: string,
  email: string | null,
): Promise<ActionResult<CardCheckout | null>> {
  // Env-guarded before anything is written: with no key the booking is left
  // exactly as it was, dates still held, and the guest is told the truth.
  if (!isPaystackConfigured()) return fail(CARD_UNCONFIGURED_MESSAGE);
  if (!email) {
    return fail(
      "Your account has no email address, which card payment needs. Add one to your profile and try again.",
    );
  }

  const admin = getAdminClient();
  if (!admin) return fail(NOT_CONFIGURED_MESSAGE);

  // What this charge is, as the database computes it now. No approved
  // agreement or no payee account means no attempt, new or reused.
  const quote = await quoteSplit(admin, booking);
  if (isRefusal(quote)) return fail(quote.message);

  /* ONE OPEN ATTEMPT PER PAYER AND CHARGE. A payer who closed the Paystack
     window, lost the tab or tapped again gets the checkout they already have
     rather than a second pending attempt, provided it is the same charge
     (same agreement, amount, split and Paystack mode) and was opened within
     the reuse window. Paystack is asked first, so a checkout that was paid,
     failed or never existed is not handed back. */
  const reused = await reuseLiveAttempt(admin, booking.id, quote, { kind: "user", userId });
  if (reused.kind === "checkout") return ok(reused.checkout);
  if (reused.kind === "paid") {
    revalidatePath("/bookings");
    revalidatePath(`/checkout/${booking.id}`);
    return fail(reused.message);
  }

  // The attempt row goes in first, with its split, so a webhook that beats
  // the redirect back has something to settle and never has to invent a
  // booking.
  const opened = await insertSplitAttempt(admin, booking, quote);
  if (isRefusal(opened)) return fail(opened.message);
  const { reference, amountMinor } = opened;

  // A rent charge comes back to /rent/pay/<inspectionId>, a stay to
  // /checkout/<bookingId>; the database decides which (lib/rent/return-path).
  const callbackUrl = `${await siteOrigin()}${await checkoutReturnPath(admin, booking.id, reference)}`;

  try {
    const tx = await initializeTransaction({
      email,
      amountMinor,
      reference,
      callbackUrl,
      metadata: {
        booking_id: booking.id,
        user_id: userId,
        agreement_id: opened.agreementId,
        purpose: "booking_payment",
      },
      split: opened.split,
    });
    /* Kept on the attempt so the next retry can resume this checkout instead
       of opening another. Best effort: without it a retry opens a new one,
       which is what happened before. */
    try {
      await recordCheckoutHandle(admin, reference, {
        accessCode: tx.accessCode,
        authorizationUrl: tx.authorizationUrl,
      });
    } catch {
      // The checkout still opens; only its reuse is lost.
    }
    return ok({
      authorizationUrl: tx.authorizationUrl,
      accessCode: tx.accessCode,
      reference,
      amountMinor,
    });
  } catch (e) {
    // The page never opened, so this attempt is dead. Marking it FAILED keeps
    // the reconciliation view honest; the booking itself is untouched.
    try {
      await markChargeFailed(admin, reference);
    } catch {
      // Reconciliation settles it against the processor's own records.
    }
    return fail(
      describePaystackError(
        e,
        "The secure payment page could not be opened. Nothing was charged and your dates are still held.",
      ),
    );
  }
}

/**
 * Open a hosted card checkout for a booking the caller owns.
 *
 * Wrapped in the idempotency guard: on a connection that drops mid-request, a
 * second tap carrying the same key replays the first authorisation URL instead
 * of opening a second charge against the same stay.
 */
export async function startCardCheckout(
  input: CheckoutInput,
): Promise<ActionResult<CardCheckout | null>> {
  const guarded = await guardPayable(input.bookingId);
  if (!guarded.ok) return guarded.result;

  const limit = await guardMoney("startCardCheckout", guarded.userId);
  if (!limit.allowed) return fail(limit.message);

  const run = await withIdempotency<ActionResult<CardCheckout | null>>(
    {
      scope: BOOKING_PAYMENT_SCOPE,
      key: input.idempotencyKey ?? null,
      subject: bookingPaymentSubject(guarded.booking.id),
      shouldRecord: (result) => result.ok,
    },
    () => withBookingOpenLock(guarded.booking.id, () => startCardCheckoutWork(guarded.booking, guarded.userId, guarded.email)),
  );

  if (run.status === "in-flight") return fail(IN_FLIGHT_MESSAGE);

  /* A REPLAY OF A CHECKOUT THAT HAS SINCE CLOSED IS NOT AN ANSWER. The same
     key replays the first answer for its lease, which is right for a double
     tap and wrong once that attempt was abandoned or failed: the payer would
     be handed a checkout the platform has already closed. Then the work runs
     again under a key derived from the closed reference (hashed, so it stays a
     fixed length however many times it is derived), so it is still claimed
     once, and it reuses or opens exactly as a fresh tap would. At most
     MAX_REPLAY_HOPS times: a chain longer than that is answered as it stands. */
  let current: IdempotentRun<ActionResult<CardCheckout | null>> = run;
  let key = input.idempotencyKey ?? null;
  for (let hop = 0; hop < MAX_REPLAY_HOPS; hop += 1) {
    if (!(current.status === "done" && current.replayed && current.result.ok && current.result.data && key)) break;
    if (!(await attemptClosed(current.result.data.reference))) break;
    key = derivedKey(key, current.result.data.reference);
    const nextKey = key;
    current = await withIdempotency<ActionResult<CardCheckout | null>>(
      {
        scope: BOOKING_PAYMENT_SCOPE,
        key: nextKey,
        subject: bookingPaymentSubject(guarded.booking.id),
        shouldRecord: (result) => result.ok,
      },
      () => withBookingOpenLock(guarded.booking.id, () => startCardCheckoutWork(guarded.booking, guarded.userId, guarded.email)),
    );
    if (current.status === "in-flight") return fail(IN_FLIGHT_MESSAGE);
  }
  return current.status === "done" ? current.result : fail(IN_FLIGHT_MESSAGE);
}

/** How many closed replays one tap may step past before answering as it stands. */
const MAX_REPLAY_HOPS = 3;

/** The key a replay of a closed attempt runs under: fixed length, one per closed reference. */
function derivedKey(key: string, closedReference: string): string {
  return createHash("sha256").update(`${key}:after:${closedReference}`).digest("hex");
}

/**
 * One attempt opens at a time per booking, whatever the key: two tabs carry
 * two idempotency keys, and both could otherwise find no live attempt and each
 * open one. The lease, and why it is a lease rather than a recorded answer or
 * an advisory lock, is in `lib/payments/booking-lease.ts`.
 */
async function withBookingOpenLock<T>(
  bookingId: string,
  work: () => Promise<ActionResult<T>>,
): Promise<ActionResult<T>> {
  const run = await withBookingOpenLease(bookingPaymentSubject(bookingId), work);
  if (run.status === "busy") return fail(IN_FLIGHT_MESSAGE);
  return run.result;
}

/** True when the attempt behind a reference has left PENDING without being paid. */
async function attemptClosed(reference: string): Promise<boolean> {
  const admin = getAdminClient();
  if (!admin) return false;
  const { data } = await admin
    .from("transactions")
    .select("status")
    .eq("provider_ref", reference)
    .maybeSingle();
  return data?.status === "ABANDONED" || data?.status === "FAILED";
}

/* ------------------------------------------------------ saved card path */

export type SavedCardInput = CheckoutInput & {
  /** Which saved card. Its token never leaves the server. */
  methodId: string;
};

async function payWithSavedCardWork(
  booking: PayableBooking,
  methodId: string,
): Promise<ActionResult<ChargeSavedCardOutcome>> {
  if (!isPaystackConfigured()) return fail(CARD_UNCONFIGURED_MESSAGE);

  const admin = getAdminClient();
  if (!admin) return fail(NOT_CONFIGURED_MESSAGE);

  /* Never beside an open hosted checkout for the same booking: the payer could
     complete both. A checkout the payer closed is released on close
     (lib/payments/attempt-actions.ts); one left open stops counting 45 minutes
     after it was last opened. */
  if (await bookingHasPaymentInFlight(admin, booking.id)) {
    return fail(
      "A card payment window is already open for this booking. Finish or close it first, so nothing is charged twice.",
    );
  }

  // The same attempt row, with the same split, the hosted path writes: a
  // saved-card charge is just a charge with a reference, settled by the
  // identical code path.
  const opened = await openSplitAttempt(admin, booking);
  if (isRefusal(opened)) return fail(opened.message);
  const { reference, amountMinor } = opened;

  const charged = await chargeSavedCard({
    methodId,
    amountMinor,
    reference,
    purpose: "booking_payment",
    metadata: { booking_id: booking.id, agreement_id: opened.agreementId },
    split: opened.split,
    callbackUrl: `${await siteOrigin()}${await checkoutReturnPath(admin, booking.id, reference)}`,
  });

  if (!charged.ok) {
    // Nothing was taken, so the attempt is dead and the booking is untouched.
    try {
      await markChargeFailed(admin, reference);
    } catch {
      // Reconciliation settles it against the processor's own records.
    }
    return charged;
  }

  if (charged.data.kind === "needs_hosted_checkout") {
    /* The fallback checkout is the same attempt under the same reference.
       Keeping its handle lets a retry resume it (lib/payments/attempts.ts)
       instead of opening a second attempt. Best effort, as on the card path. */
    try {
      await recordCheckoutHandle(admin, reference, {
        accessCode: charged.data.accessCode,
        authorizationUrl: charged.data.authorizationUrl,
      });
    } catch {
      // The checkout still opens; only its reuse is lost.
    }
  }

  if (charged.data.kind === "charged") {
    /* The processor answered synchronously, so the guest should not have to
       wait for a webhook to see their stay confirmed. This is the same
       settlement the webhook calls, keyed on the same reference, so whichever
       arrives first does the work and the second finds nothing left. */
    await settleCardPayment(reference);
  }

  return charged;
}

/**
 * Pay for a stay with a card already on the account.
 *
 * ONE ATTEMPT, NEVER A LOOP. charge_authorization cannot present a 3DS
 * challenge, so a bank that insists on authenticating declines; the fallback
 * is a hosted checkout under the SAME reference, handed back for the surface
 * to open, and the saved card is never retried. That rule lives in
 * `chargeSavedCard` so every caller inherits it.
 *
 * The idempotency guard is this module's own, under its own scope: a dropped
 * connection and a second tap carrying the same key replay the first answer
 * rather than charging a card twice for one stay.
 */
export async function payWithSavedCard(
  input: SavedCardInput,
): Promise<ActionResult<ChargeSavedCardOutcome>> {
  const guarded = await guardPayable(input.bookingId);
  if (!guarded.ok) return guarded.result;

  const limit = await guardMoney("payWithSavedCard", guarded.userId);
  if (!limit.allowed) return fail(limit.message);

  const run = await withIdempotency<ActionResult<ChargeSavedCardOutcome>>(
    {
      scope: BOOKING_PAYMENT_SCOPE,
      key: input.idempotencyKey ?? null,
      subject: bookingPaymentSubject(guarded.booking.id),
      shouldRecord: (result) => result.ok,
    },
    () => withBookingOpenLock(guarded.booking.id, () => payWithSavedCardWork(guarded.booking, input.methodId)),
  );

  if (run.status === "in-flight") return fail(IN_FLIGHT_MESSAGE);
  return run.result;
}

/* --------------------------------------------------------- return path */

/**
 * Settle a card payment on the way back from Paystack.
 *
 * The webhook is the path that runs in production, but the guest usually lands
 * back here first. This verifies the charge with the processor and then calls
 * the very same settlement the webhook calls, so whichever arrives first does
 * the work and the second finds nothing left to do.
 */
export async function settleCardPayment(
  reference: string,
): Promise<ActionResult<CardSettlement | null>> {
  const session = await resolveSession();
  if (session.state === "unconfigured") return fail(NOT_CONFIGURED_MESSAGE);
  if (session.state === "signed-out") return fail(SIGNED_OUT_MESSAGE);

  if (!isBookingReference(reference)) {
    return fail(UNKNOWN_REFERENCE_MESSAGE);
  }
  if (!isPaystackConfigured()) return fail(CARD_UNCONFIGURED_MESSAGE);

  const admin = getAdminClient();
  if (!admin) return fail(NOT_CONFIGURED_MESSAGE);

  // Exported actions are public endpoints, so the caller has to own the booking
  // this reference belongs to before anything is read from the processor.
  let owner: { bookingId: string; guestId: string } | null = null;
  try {
    owner = await bookingForReference(admin, reference);
  } catch {
    return fail(SERVICE_DOWN_MESSAGE);
  }
  if (!owner) return fail(UNKNOWN_REFERENCE_MESSAGE);
  if (owner.guestId !== session.user.id) return fail(NOT_FOUND_MESSAGE);

  let tx;
  try {
    tx = await verifyTransaction(reference);
  } catch {
    return fail(
      "The payment could not be checked just now. If you completed it, your booking confirms automatically in a moment.",
    );
  }

  if (tx.status !== "success") {
    if (tx.status === "failed" || tx.status === "reversed") {
      try {
        await markChargeFailed(admin, reference);
      } catch {
        // Reconciliation settles it; the booking is untouched either way.
      }
      return fail(
        "The payment did not go through, so nothing was charged. Your dates are still held and you can try again.",
      );
    }
    if (tx.status === "abandoned") {
      return fail(
        "The payment was not completed, so nothing was charged. Your dates are still held.",
      );
    }
    return fail("The payment is still processing. Your booking confirms the moment it settles.");
  }

  if (tx.currency !== "NGN") {
    return fail(
      "That payment was not in naira, so it was not applied to this booking. Contact support with the reference and we will trace it for you.",
    );
  }

  let settlement: Awaited<ReturnType<typeof settleBookingCharge>>;
  try {
    settlement = await settleBookingCharge(admin, {
      reference,
      amountMinor: tx.amountMinor,
      processorFeeMinor: tx.feesMinor,
      fallbackBookingId: owner.bookingId,
    });
  } catch {
    return fail(
      "The payment succeeded but could not be recorded just now. Your booking confirms automatically in a moment.",
    );
  }

  if (settlement.outcome === "unknown-reference") {
    return fail("That payment could not be matched to a booking. Our team reconciles it for you.");
  }
  if (settlement.outcome === "refund-due") {
    await refundChargeToCard(admin, {
      reference: settlement.reference || reference,
      reason: settlement.reason,
      actor: { kind: "user", userId: session.user.id },
    });
    return fail(
      "Your payment went through but could not be applied to this booking, so the whole amount is being returned to the card or account you paid with. Vallo has kept nothing. Banks usually show it within 5 to 10 working days.",
    );
  }

  const confirmed = settlement.outcome === "settled" ? settlement.confirmed : false;

  // Only a transition that actually happened here sends the email. A guest
  // whose webhook already confirmed the stay is not told twice.
  if (confirmed && settlement.outcome === "settled") {
    await sendConfirmationEmail(settlement.bookingId, settlement.totalMinor, session.user.id);
  }

  revalidatePath("/bookings");
  revalidatePath(`/checkout/${owner.bookingId}`);

  return ok({
    bookingId: owner.bookingId,
    amountMinor: settlement.outcome === "settled" ? settlement.amountMinor : tx.amountMinor,
    confirmed,
  });
}

/**
 * The confirmation the return path may send. The message itself, and who else
 * hears about the stay, live in `announceConfirmedStay`: a booking made for
 * somebody else has to reach the person actually arriving, and that decision
 * belongs in one place rather than in each of the four paths that can confirm
 * a stay. Everything is best effort and runs after the database has committed,
 * so a mail failure can never turn a paid booking into an error the guest sees.
 */
async function sendConfirmationEmail(
  bookingId: string,
  totalMinor: number,
  actingUserId: string,
): Promise<void> {
  const admin = getAdminClient();
  if (!admin) return;
  // The fast path: when the payer is the person who just tapped pay, their
  // address is already on the session and needs no lookup. Whether they really
  // are the payer is checked against the booking, not assumed here.
  const session = await resolveSession();
  await announceConfirmedStay(admin, {
    bookingId,
    totalMinor,
    actingUser:
      session.state === "signed-in"
        ? { id: actingUserId, contact: contactFromSession(session.user) }
        : null,
  });
}
