"use server";

/**
 * Booking checkout: the two ways a guest actually pays.
 *
 * Reserve inserts a PENDING booking and holds the calendar. Until this file
 * existed nothing could move money against it, so a stay could be requested
 * and never paid for. Both paths here close that loop, and both refuse rather
 * than pretend when the platform is not configured yet.
 *
 *  - startCardCheckout writes a PENDING `transactions` row whose provider_ref
 *    is a fresh `rm-book-<uuid>` reference, then opens a hosted Paystack
 *    checkout for the amount on the STORED booking row. Settlement belongs to
 *    the webhook and the return path, never to this action: nothing here marks
 *    anything paid.
 *  - payWithWallet re-prices the guest's spendable balance server side and then
 *    does everything else inside ONE database function: debit the wallet,
 *    record the transaction, write the balanced ledger row, confirm the
 *    booking, append the state event and close the calendar nights. All or
 *    nothing, because a half-paid booking is the worst state this platform
 *    could hold.
 *  - settleCardPayment is the return-from-Paystack path. It verifies with the
 *    processor and then calls the same settlement the webhook calls, so
 *    whichever arrives first wins and the second is a no-op.
 *
 * The platform charges nothing. The amount is always the booking total exactly
 * as stored, computed at reserve from the listing's own price snapshot and
 * never taken from the client (docs/MASTER_TODO.md section 5b).
 *
 * Every amount is integer kobo, end to end (Master Rule 50).
 */

import { revalidatePath } from "next/cache";
import { headers } from "next/headers";
import { fail, ok, validate, type ActionResult } from "../actions/envelope";
import {
  NOT_CONFIGURED_MESSAGE,
  SIGNED_OUT_MESSAGE,
  resolveSession,
} from "../actions/session";
import { bestEffortEmail, sendEmail } from "../email/client";
import { bookingConfirmed } from "../email/messages";
import { contactForUser, contactFromSession } from "../email/recipients";
import { isFeatureEnabled } from "../flags";
import { nairaExact } from "../payments/money";
import {
  PaystackError,
  initializeTransaction,
  isPaystackConfigured,
  verifyTransaction,
} from "../payments/paystack";
import { bookingReference, isBookingReference } from "../payments/references";
import { IN_FLIGHT_MESSAGE, withIdempotency } from "../security/idempotency";
import { subjectForUser } from "../security/rate-limit";
import { availableBalanceMinor, ensureWalletId, getAdminClient } from "../wallet/ledger";
import { cancelInputSchema } from "./schema";
import { bookingForReference, markChargeFailed, settleBookingCharge } from "./settlement";

const PAUSED_MESSAGE =
  "Bookings are paused for maintenance. Please try again in a little while.";

const CARD_UNCONFIGURED_MESSAGE =
  "Card payment switches on the moment payment keys land. Your booking is untouched and your dates are still held.";

const WALLET_OFF_MESSAGE =
  "The wallet is switched off for a moment while we make improvements. Please try again shortly.";

const NOT_FOUND_MESSAGE = "We could not find that booking on your account.";

const ALREADY_PAID_MESSAGE = "This booking is already paid, so there is nothing to pay again.";

const CANCELLED_MESSAGE =
  "This booking was cancelled, so it cannot be paid. Search again and pick new dates.";

/**
 * Kept for the one case that still means it: the database refused because the
 * booking left a payable state between the guard's read and the write. It is no
 * longer said about a CONFIRMED booking, because a confirmed stay can still be
 * unpaid and telling that guest "nothing further is needed" was simply false.
 */
const CONFIRMED_MESSAGE = "This booking is already confirmed. Nothing further is needed.";

const SERVICE_DOWN_MESSAGE =
  "Payment is temporarily unavailable. Your booking is unchanged. Please try again shortly.";

/* ------------------------------------------------------------------ shapes */

export type CheckoutInput = {
  bookingId: string;
  /**
   * One key per submit, generated by the surface. A dropped connection and a
   * second tap carry the same key, so the retry replays the first answer
   * instead of paying twice.
   */
  idempotencyKey?: string;
};

export type CardCheckout = {
  /** Where to send the guest to pay. */
  authorizationUrl: string;
  reference: string;
  amountMinor: number;
};

export type WalletPayment = {
  bookingId: string;
  amountMinor: number;
  reference: string;
  /** The spendable balance left after the payment, in kobo. */
  balanceAfterMinor: number;
};

export type CardSettlement = {
  bookingId: string;
  amountMinor: number;
  /** True when this call moved the booking to CONFIRMED. */
  confirmed: boolean;
};

/** The booking row a payment path is allowed to act on. */
type PayableBooking = {
  id: string;
  listing_id: string;
  guest_id: string;
  status: "PENDING" | "CONFIRMED" | "CANCELLED";
  check_in: string;
  check_out: string;
  nights: number;
  total_minor: number;
  currency: string;
};

/** Where a hosted checkout sends the guest back to. */
async function siteOrigin(): Promise<string> {
  const explicit = process.env.NEXT_PUBLIC_SITE_URL ?? "";
  if (explicit.length > 0) return explicit.replace(/\/+$/, "");
  const h = await headers();
  const host = h.get("x-forwarded-host") ?? h.get("host");
  const proto = h.get("x-forwarded-proto") ?? "https";
  return host ? `${proto}://${host}` : "http://localhost:3000";
}

/** Keep a processor's own words, without ever surfacing a raw code. */
function describePaystackError(e: unknown, fallback: string): string {
  if (e instanceof PaystackError && e.status !== 401 && e.message.trim().length > 0) {
    return `${fallback} The payment service said: ${e.message.trim()}`;
  }
  return fallback;
}

/* --------------------------------------------------------- shared guards */

type Guarded =
  | { ok: false; result: ActionResult<null> }
  | {
      ok: true;
      booking: PayableBooking;
      userId: string;
      email: string | null;
      displayName: string | null;
    };

/**
 * Prove the caller owns this booking and that it can still be paid.
 *
 * Ownership comes from reading through the caller's OWN RLS-bound client: a
 * booking that is not theirs simply does not come back, so the database is the
 * authority on identity rather than a check this code could forget. The amount
 * is read here and used everywhere after, so no payment path can be handed a
 * figure by a client.
 */
async function guardPayable(bookingId: string): Promise<Guarded> {
  const session = await resolveSession();
  if (session.state === "unconfigured") return { ok: false, result: fail(NOT_CONFIGURED_MESSAGE) };
  if (session.state === "signed-out") return { ok: false, result: fail(SIGNED_OUT_MESSAGE) };

  if (!(await isFeatureEnabled("bookings"))) return { ok: false, result: fail(PAUSED_MESSAGE) };

  const parsed = validate(cancelInputSchema, { bookingId });
  if (!parsed.ok) return { ok: false, result: fail(parsed.error, parsed.fieldErrors) };

  const { data: booking, error } = await session.supabase
    .from("bookings")
    .select("id, listing_id, guest_id, status, check_in, check_out, nights, total_minor, currency")
    .eq("id", parsed.data.bookingId)
    .maybeSingle();

  if (error) return { ok: false, result: fail(SERVICE_DOWN_MESSAGE) };
  if (!booking) return { ok: false, result: fail(NOT_FOUND_MESSAGE) };
  if (booking.status === "CANCELLED") return { ok: false, result: fail(CANCELLED_MESSAGE) };
  // CONFIRMED is deliberately payable. A request-to-book stay is confirmed by
  // the host accepting it, not by money arriving, so refusing CONFIRMED here
  // meant an accepted stay could never be paid on the platform at all: the
  // guest was told "nothing further is needed" while the host was never paid.
  // What decides whether there is anything left to pay is a settled payment
  // attempt, checked a few lines below, and that is the only honest test.
  if (booking.currency !== "NGN") {
    return {
      ok: false,
      result: fail("This booking is not priced in naira, so it cannot be paid here."),
    };
  }
  if (booking.total_minor <= 0) {
    return {
      ok: false,
      result: fail("This booking has no amount to pay. Contact support and we will sort it out."),
    };
  }

  // A booking with a settled attempt is paid, whatever its status says. Reading
  // it through the caller's own client keeps this inside their own visibility.
  const { data: settled } = await session.supabase
    .from("transactions")
    .select("id")
    .eq("booking_id", booking.id)
    .eq("status", "SUCCESSFUL")
    .limit(1);
  if ((settled?.length ?? 0) > 0) return { ok: false, result: fail(ALREADY_PAID_MESSAGE) };

  const metadataName = session.user.user_metadata["full_name"] as string | undefined;
  const name = (metadataName ?? "").trim();

  return {
    ok: true,
    booking: booking as PayableBooking,
    userId: session.user.id,
    email: session.user.email ?? null,
    displayName: name.length > 0 ? name : null,
  };
}

/* ------------------------------------------------------------ card path */

async function startCardCheckoutWork(
  booking: PayableBooking,
  userId: string,
  email: string | null,
): Promise<ActionResult<CardCheckout | null>> {
  // Env-guarded before anything is written: with no key the booking is left
  // exactly as it was, dates still held, and the guest is told the truth.
  if (!isPaystackConfigured()) return fail(CARD_UNCONFIGURED_MESSAGE);
  if (!email) {
    return fail(
      "Your account has no email address, which card payment needs. Add one to your profile and try again.",
    );
  }

  const admin = getAdminClient();
  if (!admin) return fail(NOT_CONFIGURED_MESSAGE);

  const amountMinor = booking.total_minor;
  const reference = bookingReference();

  // The attempt row goes in first, so a webhook that beats the redirect back
  // has something to settle and never has to invent a booking.
  const attempt = await admin.from("transactions").insert({
    booking_id: booking.id,
    provider: "paystack",
    provider_ref: reference,
    amount_minor: amountMinor,
    currency: booking.currency,
    status: "PENDING",
  });
  if (attempt.error) return fail(SERVICE_DOWN_MESSAGE);

  const callbackUrl = `${await siteOrigin()}/checkout/${booking.id}?paid=1&reference=${reference}`;

  try {
    const tx = await initializeTransaction({
      email,
      amountMinor,
      reference,
      callbackUrl,
      metadata: {
        booking_id: booking.id,
        user_id: userId,
        purpose: "booking_payment",
      },
    });
    return ok({ authorizationUrl: tx.authorizationUrl, reference, amountMinor });
  } catch (e) {
    // The page never opened, so this attempt is dead. Marking it FAILED keeps
    // the reconciliation view honest; the booking itself is untouched.
    try {
      await markChargeFailed(admin, reference);
    } catch {
      // Reconciliation settles it against the processor's own records.
    }
    return fail(
      describePaystackError(
        e,
        "The secure payment page could not be opened. Nothing was charged and your dates are still held.",
      ),
    );
  }
}

/**
 * Open a hosted card checkout for a booking the caller owns.
 *
 * Wrapped in the idempotency guard: on a connection that drops mid-request, a
 * second tap carrying the same key replays the first authorisation URL instead
 * of opening a second charge against the same stay.
 */
export async function startCardCheckout(
  input: CheckoutInput,
): Promise<ActionResult<CardCheckout | null>> {
  const guarded = await guardPayable(input.bookingId);
  if (!guarded.ok) return guarded.result;

  const run = await withIdempotency<ActionResult<CardCheckout | null>>(
    {
      scope: "booking.card_checkout",
      key: input.idempotencyKey ?? null,
      subject: subjectForUser(guarded.userId),
      shouldRecord: (result) => result.ok,
    },
    () => startCardCheckoutWork(guarded.booking, guarded.userId, guarded.email),
  );

  if (run.status === "in-flight") return fail(IN_FLIGHT_MESSAGE);
  return run.result;
}

/* ---------------------------------------------------------- wallet path */

/**
 * The atomic wallet payment, reached by name because it is a money-critical
 * door defined once in SQL and called from exactly here. The generated types
 * do not carry it, so the client is narrowed to the single method used rather
 * than the whole surface being loosened.
 */
type RpcCaller = {
  rpc: (
    fn: string,
    args: Record<string, unknown>,
  ) => PromiseLike<{ data: unknown; error: { message?: string | null } | null }>;
};

type WalletPayOutcome =
  | { status: "ok"; amount_minor?: number; reference?: string }
  | { status: "insufficient"; available_minor?: number }
  | { status: string; available_minor?: number };

function readOutcome(data: unknown): WalletPayOutcome | null {
  if (typeof data !== "object" || data === null || Array.isArray(data)) return null;
  const status = (data as Record<string, unknown>).status;
  if (typeof status !== "string") return null;
  const available = (data as Record<string, unknown>).available_minor;
  return {
    status,
    ...(typeof available === "number" ? { available_minor: available } : {}),
  };
}

async function payWithWalletWork(
  booking: PayableBooking,
  userId: string,
  email: string | null,
  displayName: string | null,
): Promise<ActionResult<WalletPayment | null>> {
  if (!(await isFeatureEnabled("wallet"))) return fail(WALLET_OFF_MESSAGE);

  const admin = getAdminClient();
  if (!admin) return fail(NOT_CONFIGURED_MESSAGE);

  const amountMinor = booking.total_minor;
  const reference = bookingReference();

  // A first read of the spendable balance, so a guest who plainly cannot afford
  // the stay is told so without a write being attempted. The figure that
  // actually decides the payment is re-read inside the database function, under
  // a row lock, because only that one can be trusted against a concurrent spend.
  let available: number;
  try {
    const walletId = await ensureWalletId(admin, userId);
    available = await availableBalanceMinor(admin, walletId);
  } catch {
    return fail(SERVICE_DOWN_MESSAGE);
  }

  if (available < amountMinor) {
    return fail(
      `Your available wallet balance is ${nairaExact(available)}, and this stay comes to ${nairaExact(amountMinor)}. Add money to your wallet or pay by card.`,
    );
  }

  let outcome: WalletPayOutcome | null = null;
  try {
    const caller = admin as unknown as RpcCaller;
    const { data, error } = await caller.rpc("pay_booking_from_wallet", {
      payer: userId,
      target_booking: booking.id,
      payment_reference: reference,
    });
    if (error) return fail(SERVICE_DOWN_MESSAGE);
    outcome = readOutcome(data);
  } catch {
    return fail(SERVICE_DOWN_MESSAGE);
  }

  if (!outcome) return fail(SERVICE_DOWN_MESSAGE);

  if (outcome.status === "insufficient") {
    const exact = typeof outcome.available_minor === "number" ? outcome.available_minor : available;
    return fail(
      `Your available wallet balance is ${nairaExact(exact)}, and this stay comes to ${nairaExact(amountMinor)}. Add money to your wallet or pay by card.`,
    );
  }
  if (outcome.status === "not_payable") return fail(CANCELLED_MESSAGE);
  if (outcome.status === "not_pending") return fail(CONFIRMED_MESSAGE);
  if (outcome.status === "not_found") return fail(NOT_FOUND_MESSAGE);
  if (outcome.status === "already_paid") return fail(ALREADY_PAID_MESSAGE);
  if (outcome.status !== "ok" && outcome.status !== "duplicate") return fail(SERVICE_DOWN_MESSAGE);

  // Everything committed together or not at all. Reading the balance back is
  // display only and must never turn a paid stay into an error.
  let balanceAfterMinor = available - amountMinor;
  try {
    const walletId = await ensureWalletId(admin, userId);
    balanceAfterMinor = await availableBalanceMinor(admin, walletId);
  } catch {
    // Keep the arithmetic figure; the wallet page re-reads the real one.
  }

  revalidatePath("/bookings");
  revalidatePath("/wallet");
  revalidatePath(`/checkout/${booking.id}`);

  // The booking is CONFIRMED in the database. Telling the guest is best effort:
  // the confirmation stands whether or not the email leaves.
  await bestEffortEmail(async () => {
    const contact =
      email !== null
        ? { email, name: displayName }
        : await contactForUser(admin, booking.guest_id);
    if (!contact) return;
    const { data: listing } = await admin
      .from("listings")
      .select("title")
      .eq("id", booking.listing_id)
      .maybeSingle();
    const title = (listing?.title ?? "").trim();
    const message = bookingConfirmed({
      guestName: contact.name,
      listingTitle: title.length > 0 ? title : "your stay",
      checkIn: booking.check_in,
      checkOut: booking.check_out,
      nights: booking.nights,
      totalMinor: amountMinor,
    });
    await sendEmail({ to: contact.email, subject: message.subject, html: message.html });
  });

  return ok({ bookingId: booking.id, amountMinor, reference, balanceAfterMinor });
}

/**
 * Pay a booking from the guest's own RentMe wallet.
 *
 * The spendable balance is re-checked server side and then again inside the
 * database function under a row lock, so two taps racing each other cannot both
 * spend the last naira. Wrapped in the idempotency guard as well, so a retry on
 * a dropped connection replays the first receipt.
 */
export async function payWithWallet(
  input: CheckoutInput,
): Promise<ActionResult<WalletPayment | null>> {
  const guarded = await guardPayable(input.bookingId);
  if (!guarded.ok) return guarded.result;

  const run = await withIdempotency<ActionResult<WalletPayment | null>>(
    {
      scope: "booking.wallet_payment",
      key: input.idempotencyKey ?? null,
      subject: subjectForUser(guarded.userId),
      shouldRecord: (result) => result.ok,
    },
    () =>
      payWithWalletWork(guarded.booking, guarded.userId, guarded.email, guarded.displayName),
  );

  if (run.status === "in-flight") return fail(IN_FLIGHT_MESSAGE);
  return run.result;
}

/* --------------------------------------------------------- return path */

/**
 * Settle a card payment on the way back from Paystack.
 *
 * The webhook is the path that runs in production, but the guest usually lands
 * back here first. This verifies the charge with the processor and then calls
 * the very same settlement the webhook calls, so whichever arrives first does
 * the work and the second finds nothing left to do.
 */
export async function settleCardPayment(
  reference: string,
): Promise<ActionResult<CardSettlement | null>> {
  const session = await resolveSession();
  if (session.state === "unconfigured") return fail(NOT_CONFIGURED_MESSAGE);
  if (session.state === "signed-out") return fail(SIGNED_OUT_MESSAGE);

  if (!isBookingReference(reference)) {
    return fail("That payment reference is not recognised.");
  }
  if (!isPaystackConfigured()) return fail(CARD_UNCONFIGURED_MESSAGE);

  const admin = getAdminClient();
  if (!admin) return fail(NOT_CONFIGURED_MESSAGE);

  // Exported actions are public endpoints, so the caller has to own the booking
  // this reference belongs to before anything is read from the processor.
  let owner: { bookingId: string; guestId: string } | null = null;
  try {
    owner = await bookingForReference(admin, reference);
  } catch {
    return fail(SERVICE_DOWN_MESSAGE);
  }
  if (!owner) return fail("That payment reference is not recognised.");
  if (owner.guestId !== session.user.id) return fail(NOT_FOUND_MESSAGE);

  let tx;
  try {
    tx = await verifyTransaction(reference);
  } catch {
    return fail(
      "The payment could not be checked just now. If you completed it, your booking confirms automatically in a moment.",
    );
  }

  if (tx.status !== "success") {
    if (tx.status === "failed" || tx.status === "reversed") {
      try {
        await markChargeFailed(admin, reference);
      } catch {
        // Reconciliation settles it; the booking is untouched either way.
      }
      return fail(
        "The payment did not go through, so nothing was charged. Your dates are still held and you can try again.",
      );
    }
    if (tx.status === "abandoned") {
      return fail(
        "The payment was not completed, so nothing was charged. Your dates are still held.",
      );
    }
    return fail("The payment is still processing. Your booking confirms the moment it settles.");
  }

  if (tx.currency !== "NGN") {
    return fail("That payment was not in naira, so it was not applied to this booking.");
  }

  let settlement: Awaited<ReturnType<typeof settleBookingCharge>>;
  try {
    settlement = await settleBookingCharge(admin, {
      reference,
      amountMinor: tx.amountMinor,
      processorFeeMinor: tx.feesMinor,
      fallbackBookingId: owner.bookingId,
    });
  } catch {
    return fail(
      "The payment succeeded but could not be recorded just now. Your booking confirms automatically in a moment.",
    );
  }

  if (settlement.outcome === "unknown-reference") {
    return fail("That payment could not be matched to a booking. Our team reconciles it for you.");
  }

  const confirmed = settlement.outcome === "settled" ? settlement.confirmed : false;

  // Only a transition that actually happened here sends the email. A guest
  // whose webhook already confirmed the stay is not told twice.
  if (confirmed && settlement.outcome === "settled") {
    await sendConfirmationEmail(settlement.bookingId, settlement.ledger.grossMinor, session.user.id);
  }

  revalidatePath("/bookings");
  revalidatePath(`/checkout/${owner.bookingId}`);

  return ok({
    bookingId: owner.bookingId,
    amountMinor: settlement.outcome === "settled" ? settlement.amountMinor : tx.amountMinor,
    confirmed,
  });
}

/**
 * The one confirmation email the return path may send. Everything about it is
 * best effort and it runs after the database has committed, so a mail failure
 * can never turn a paid booking into an error the guest sees.
 */
async function sendConfirmationEmail(
  bookingId: string,
  totalMinor: number,
  actingUserId: string,
): Promise<void> {
  const admin = getAdminClient();
  if (!admin) return;
  await bestEffortEmail(async () => {
    const { data: booking } = await admin
      .from("bookings")
      .select("guest_id, check_in, check_out, nights, listing_id")
      .eq("id", bookingId)
      .maybeSingle();
    if (!booking) return;

    const session = await resolveSession();
    const guest =
      session.state === "signed-in" && booking.guest_id === actingUserId
        ? contactFromSession(session.user)
        : await contactForUser(admin, booking.guest_id);
    if (!guest) return;

    const { data: listing } = await admin
      .from("listings")
      .select("title")
      .eq("id", booking.listing_id)
      .maybeSingle();
    const title = (listing?.title ?? "").trim();

    const message = bookingConfirmed({
      guestName: guest.name,
      listingTitle: title.length > 0 ? title : "your stay",
      checkIn: booking.check_in,
      checkOut: booking.check_out,
      nights: booking.nights,
      totalMinor,
    });
    await sendEmail({ to: guest.email, subject: message.subject, html: message.html });
  });
}
