import { namesMatch } from "./name-match";
import { isVnin, normaliseVnin } from "./nin";
import type { IdentityProvider } from "./provider";

/**
 * THE vNIN IDENTITY CHECK (V-49), with every effect injected so the whole
 * decision is proven with the stub provider. Production wiring: `actions.ts`.
 *
 * A clean match (NIMC knows the vNIN, and the legal name matches the
 * application by the Nigerian-name rule) PASSES the identity rung with the
 * vNIN service named as the decider. Anything else is recorded and left
 * PENDING for the human desk with the reason, never failed by a machine: a
 * broken NIMC record is common and is a question for a person.
 *
 * NO LIVENESS. The vNIN token is generated by the NIN holder on the
 * NIN-linked phone for this merchant, which is what this check rests on. No
 * selfie is captured anywhere in the product, so no face score is claimed.
 */

export type VninCheckDeps = {
  provider: IdentityProvider;
  hmac(nin: string): string;
  /** `public.record_vnin_check`, as the service role. */
  record(input: {
    userId: string;
    legalName: string;
    ninHmac: string;
    reference: string;
    matched: boolean;
    note: string;
  }): Promise<string>;
};

export type VninOutcome =
  | { status: "passed" }
  | { status: "pending"; reason: string }
  | { status: "refused"; reason: "invalid_token" | "unconfigured" | "not_found" | "expired" | "failed" | "no_agent" };

export async function runVninCheck(
  deps: VninCheckDeps,
  input: { userId: string; vnin: string; applicationName: string },
): Promise<VninOutcome> {
  if (!isVnin(input.vnin)) return { status: "refused", reason: "invalid_token" };
  const answer = await deps.provider.verifyVnin({ vnin: normaliseVnin(input.vnin) });
  if (!answer.ok) return { status: "refused", reason: answer.reason };

  const name = namesMatch(answer.legalName, input.applicationName);
  const matched = name.match;
  const note = matched
    ? `Name check: ${name.reason}.`
    : `NIMC name ${answer.legalName} against application name ${input.applicationName}: ${name.reason}.`;

  let result: string;
  try {
    result = await deps.record({
      userId: input.userId,
      legalName: answer.legalName,
      ninHmac: deps.hmac(answer.nin),
      reference: answer.reference,
      matched,
      note,
    });
  } catch {
    return { status: "refused", reason: "failed" };
  }
  if (result === "passed") return { status: "passed" };
  if (result === "no_agent") return { status: "refused", reason: "no_agent" };
  if (result === "nin_elsewhere") return { status: "pending", reason: "nin_elsewhere" };
  if (result === "pending") return { status: "pending", reason: "name" };
  return { status: "refused", reason: "failed" };
}
