import "server-only";

import type { SupabaseClient } from "@supabase/supabase-js";

import type { Database } from "../supabase/database.types";

/**
 * The reservations table as this module writes it.
 *
 * `database.types.ts` is regenerated by the lead when a phase closes, and
 * until the b3 migration is applied and the types regenerated it does not
 * carry `reservations.conversation_id`. The one write that stamps it, and the
 * reads that select it, go through this narrow type so the rest of the module
 * stays on the generated `Database` type. This is the same device
 * `lib/stays/db.ts` uses for M1 to M9, and it is the only cast in
 * lib/reservations.
 */

export type ReservationStatus = Database["public"]["Enums"]["booking_status"];

export type ReservationRow = {
  id: string;
  listing_id: string | null;
  business_id: string | null;
  guest_id: string;
  party_size: number;
  reserved_for: string;
  status: ReservationStatus;
  note: string | null;
  responded_at: string | null;
  conversation_id: string | null;
  created_at: string;
  updated_at: string;
};

type Table<Row> = {
  Row: Row;
  Insert: Partial<Row>;
  Update: Partial<Row>;
  Relationships: [];
};

export type ReservationsDatabase = {
  public: {
    Tables: {
      reservations: Table<ReservationRow>;
      listings: Table<{ id: string; title: string; area: string | null; city: string | null; is_demo: boolean; agent_id: string }>;
      businesses: Table<{ id: string; name: string; area: string | null; city: string | null; is_demo: boolean; owner_id: string | null }>;
      profiles: Table<{ id: string; display_name: string | null }>;
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};

export type ReservationsClient = SupabaseClient<ReservationsDatabase>;

/** The caller's own RLS-bound client, narrowed to the reservation tables. */
export function reservationsClient(supabase: SupabaseClient<Database>): ReservationsClient {
  return supabase as unknown as ReservationsClient;
}
