import "server-only";

import type { SupabaseClient } from "@supabase/supabase-js";

import type { Database } from "../supabase/database.types";

/**
 * The rent tables as this module types them.
 *
 * `database.types.ts` is regenerated by the lead when a phase closes and does
 * not carry `rent_payments` or the `open_rent_charge` door until the b3
 * migration is applied. This narrow type is the one cast in lib/rent, the
 * same device `lib/stays/db.ts` uses for M1 to M9: every query below it is
 * typed, and the cast is replaced by the generated type when it lands.
 */

export type RentPaymentRow = {
  id: string;
  inspection_id: string;
  listing_id: string;
  tenant_id: string;
  lister_id: string;
  booking_id: string;
  move_in: string;
  rent_period: "month" | "quarter" | "year";
  rent_minor: number | null;
  caution_minor: number | null;
  service_minor: number | null;
  agency_minor: number | null;
  legal_minor: number | null;
  agreement_minor: number | null;
  total_minor: number;
  total_stated: boolean;
  currency: string;
  created_at: string;
  updated_at: string;
};

/** What `public.open_rent_charge` answers. */
export type OpenRentChargeOutcome = {
  status:
    | "ok"
    | "exists"
    | "bad_request"
    | "move_in_past"
    | "not_found"
    | "not_accepted"
    | "not_published"
    | "not_a_rental"
    | "no_lister"
    | "own_listing"
    | "no_amount";
  rent_payment_id?: string;
  booking_id?: string;
  total_minor?: number;
  state?: string;
};

type Table<Row> = {
  Row: Row;
  Insert: Record<string, never>;
  Update: Record<string, never>;
  Relationships: [];
};

export type RentDatabase = {
  public: {
    Tables: {
      rent_payments: Table<RentPaymentRow>;
    };
    Views: Record<string, never>;
    Functions: {
      open_rent_charge: {
        Args: { p_tenant: string; p_inspection: string; p_move_in: string };
        Returns: OpenRentChargeOutcome;
      };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};

export type RentClient = SupabaseClient<RentDatabase>;

/** Any Supabase client (the caller's own, or the service role), narrowed to the rent tables. */
export function rentClient(supabase: SupabaseClient<Database>): RentClient {
  return supabase as unknown as RentClient;
}

/** Reads `open_rent_charge`'s answer defensively: anything else is a service fault. */
export function readOpenOutcome(data: unknown): OpenRentChargeOutcome | null {
  if (typeof data !== "object" || data === null || Array.isArray(data)) return null;
  const status = (data as Record<string, unknown>).status;
  if (typeof status !== "string") return null;
  const out: OpenRentChargeOutcome = { status: status as OpenRentChargeOutcome["status"] };
  const record = data as Record<string, unknown>;
  if (typeof record.rent_payment_id === "string") out.rent_payment_id = record.rent_payment_id;
  if (typeof record.booking_id === "string") out.booking_id = record.booking_id;
  if (typeof record.total_minor === "number") out.total_minor = record.total_minor;
  if (typeof record.state === "string") out.state = record.state;
  return out;
}
